import { Command } from "commander";
import { VERSION } from "../build-info.js";
import { registerInitCommand } from "./deprecated.js";
import { registerAgentCommand } from "./agent.js";
import { registerTopicsCommand } from "./topics.js";
import { registerAuthCommand } from "./auth.js";
import { registerVaultCommand } from "./vault.js";
import { registerTelegramCommand } from "./telegram.js";
import { registerMemoryCommand } from "./memory.js";
import { registerWebCommand } from "./web.js";
import { registerSetupCommand } from "./setup.js";
import { registerDoctorCommand } from "./doctor.js";
import { registerUpdateCommand } from "./update.js";
import { registerRestartCommand } from "./restart.js";
import { registerVersionCommand } from "./version.js";
import { registerVersionsCommand } from "./versions.js";
import { registerHandoffCommand } from "./handoff.js";
import { registerIssuesCommand } from "./issues.js";
import { registerDepsCommand } from "./deps.js";
import { registerWorkspaceCommand } from "./workspace.js";
import { registerDebugCommand } from "./debug.js";
import { registerWorktreeCommand } from "./worktree.js";
import { registerDriveCommand } from "./drive.js";
import { registerUpCommand } from "./deprecated.js";
import { registerApplyCommand } from "./apply.js";
import { registerSecretDetectCommand } from "./secret-detect.js";
import { registerStatusAskCommand } from "./status-ask.js";
import { registerAgentConfigCommands } from "./agent-config.js";
import { registerAgentConfigWriteCommands } from "./agent-config-write.js";
import { registerAgentConfigMcpCommand } from "./mcp-agent-config.js";
import { registerMigrateCommand } from "./migrate.js";
import { captureEvent, installGlobalErrorHandlers } from "../analytics/posthog.js";

installGlobalErrorHandlers();

// VERSION is sourced from src/build-info.ts (auto-generated by
// scripts/build.mjs from package.json). Reading package.json at runtime
// would break under `bun build --compile` because the source paths
// don't exist in the bundled binary's virtual filesystem.
export const program = new Command()
  .name("switchroom")
  .description(
    "Multi-agent orchestrator for Claude Code. One Telegram group, many specialized agents."
  )
  .version(VERSION)
  .option("-c, --config <path>", "Path to switchroom.yaml config file")
  .hook("preAction", async (_thisCommand, actionCommand) => {
    await captureEvent("cli_command_invoked", {
      command: actionCommand.name(),
      version: VERSION,
      node_version: process.version,
      platform: process.platform,
    });
  });

registerSetupCommand(program);
registerDoctorCommand(program);
registerUpdateCommand(program);
registerRestartCommand(program);
registerVersionCommand(program);
registerVersionsCommand(program);
registerInitCommand(program);
registerAgentCommand(program);
registerTopicsCommand(program);
registerAuthCommand(program);
registerVaultCommand(program);
registerTelegramCommand(program);
registerMemoryCommand(program);
registerWebCommand(program);
registerHandoffCommand(program);
registerIssuesCommand(program);
registerDepsCommand(program);
registerWorkspaceCommand(program);
registerDebugCommand(program);
registerWorktreeCommand(program);
registerDriveCommand(program);
registerUpCommand(program);
registerApplyCommand(program);
registerSecretDetectCommand(program);
registerStatusAskCommand(program);
registerAgentConfigCommands(program);
registerAgentConfigWriteCommands(program);
registerAgentConfigMcpCommand(program);
registerMigrateCommand(program);
