/**
 * Single source of truth for *generating + writing* the fleet compose file.
 *
 * Extracted from `apply` so that BOTH `switchroom apply` and the
 * `agent restart` reconcile path emit byte-identical compose output — they
 * can never drift. This closes the gotcha behind the v0.14.92 roll
 * (memory `agent-restart-needs-apply-for-pin`): a `release.pin` bump in
 * switchroom.yaml reached the scaffold via `agent restart` but NOT the
 * compose image refs, because restart re-emitted the agent-dir layer only
 * and left the compose (hence the running image) on the old pin. Restart now
 * regenerates the compose, so "edit switchroom.yaml → restart → done" — the
 * promise `reconcileAndRestartAgent`'s own docstring already made — actually
 * holds for image/pin changes too.
 */

import { chownSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, join } from "node:path";
import type { SwitchroomConfig } from "../config/schema.js";
import { generateCompose } from "../agents/compose.js";
import { resolveImageTag, resolveRelease, type ReleaseBlockShape } from "../config/release-resolve.js";
import { isDockerRuntime } from "../runtime-mode.js";
import { resolveOperatorUid } from "./operator-uid.js";

export interface WriteComposeOpts {
  config: SwitchroomConfig;
  composePath: string;
  /** Bind-mounted switchroom.yaml path baked into broker/kernel/scheduler. */
  switchroomConfigPath: string | undefined;
  /** CLI `--pin`/`--channel` override (apply/update). Restart passes none → uses config.release. */
  releaseOverride?: ReleaseBlockShape | undefined;
  buildMode?: "pull" | "local";
  buildContext?: string | undefined;
}

export interface WriteComposeResult {
  composePath: string;
  imageTag: string;
  bytes: number;
  /** True when the new content differs from what was on disk. */
  changed: boolean;
  /** The agent image tag previously on disk (for drift logging), or null. */
  previousImageTag: string | null;
}

const AGENT_IMAGE_TAG_RE = /image:\s*\S*switchroom-agent:(\S+)/;

/** Container path prefix that the CLI uses for bind-mounted config. */
const CONTAINER_CONFIG_PREFIX = "/state/config/";

/**
 * Translate a raw switchroom.yaml path to a HOST-filesystem path suitable
 * for use as a Docker bind-mount source.
 *
 * Problem: when `switchroom apply` (or `agent restart`) runs inside an agent
 * container, `findConfigFile()` returns `SWITCHROOM_CONFIG` which is the
 * CONTAINER path `/state/config/switchroom.yaml`. Emitting that path verbatim
 * as a bind-mount source causes Docker to auto-create an empty directory at
 * that path on the host. The vault-broker then tries to read it as a file
 * and crashes with EISDIR (2026-06-11 rollback-to-v0.15.3 incident).
 *
 * Fix: when running inside a Docker container AND the config path starts with
 * `/state/config/`, translate it to the host path using the `SWITCHROOM_HOST_HOME`
 * env var that `compose.ts` bakes into every agent container at apply time.
 * The mapping is: `/state/config/<file>` → `<SWITCHROOM_HOST_HOME>/.switchroom/<file>`.
 *
 * If we are in a container context but `SWITCHROOM_HOST_HOME` is not set (e.g.
 * the fleet was generated by a pre-fix version of switchroom), we refuse to
 * proceed rather than emit a broken compose file. The operator can resolve this
 * by running `switchroom apply` once from the HOST (which writes the new env var
 * into the compose, which then makes in-container apply safe).
 *
 * On non-container hosts the path is returned unchanged.
 */
export function resolveHostSwitchroomConfigPath(rawPath: string): string {
  if (!isDockerRuntime()) {
    // Running on the host — the path is already a valid host path.
    return rawPath;
  }
  if (!rawPath.startsWith(CONTAINER_CONFIG_PREFIX)) {
    // Not a container-config path (e.g. operator passed --config /some/host/path
    // explicitly via a bind mount). Trust it — the operator knows what they're doing.
    return rawPath;
  }
  const hostHome = process.env.SWITCHROOM_HOST_HOME;
  if (!hostHome || hostHome.length === 0) {
    throw new Error(
      `switchroom apply: running inside a container but SWITCHROOM_HOST_HOME is not set.\n` +
      `The config path "${rawPath}" is a container-internal path — emitting it as a ` +
      `Docker bind-mount source would cause Docker to create an empty directory at that ` +
      `path on the host, crashing the vault-broker and auth-broker with EISDIR.\n\n` +
      `Recovery: run \`switchroom apply\` once from the HOST (not from inside the container). ` +
      `That will regenerate the compose file with SWITCHROOM_HOST_HOME set, after which ` +
      `in-container apply will work correctly.`,
    );
  }
  // `/state/config/switchroom.yaml` → `<hostHome>/.switchroom/switchroom.yaml`
  const filename = basename(rawPath);
  return join(hostHome, ".switchroom", filename);
}

/** Generate the compose content and write it (mode 0600). Always writes — same as apply. */
export async function writeComposeFile(opts: WriteComposeOpts): Promise<WriteComposeResult> {
  const release = resolveRelease({ override: opts.releaseOverride, root: opts.config.release });
  const imageTag = resolveImageTag(release);
  const operatorUid = resolveOperatorUid();

  // Translate container-internal config paths to host paths before baking
  // them into the compose file's bind-mount sources. Without this, running
  // `switchroom apply` from inside a container emits the container path
  // `/state/config/switchroom.yaml` as the bind-mount SOURCE, causing Docker
  // to auto-create that path as an empty directory on the host and crashing
  // the vault-broker / auth-broker with EISDIR. See resolveHostSwitchroomConfigPath.
  const resolvedConfigPath = opts.switchroomConfigPath !== undefined
    ? resolveHostSwitchroomConfigPath(opts.switchroomConfigPath)
    : undefined;

  const content = generateCompose({
    config: opts.config,
    imageTag,
    buildMode: opts.buildMode ?? "pull",
    buildContext: opts.buildContext,
    // Bake the operator's HOME absolute path into volume sources (avoids
    // `${HOME}` resolving to /root under sudo). Inside a container, homedir()
    // returns the container user's home — so we prefer SWITCHROOM_HOST_HOME
    // when available (it's baked in by compose.ts at apply time).
    homeDir: process.env.SWITCHROOM_HOST_HOME || homedir(),
    // Home for FILESYSTEM probes (existsSync/mkdirSync gating optional mounts).
    // Unlike homeDir, this is the CONTAINER-REAL home — `homedir()` is
    // `/host-home` inside hostd (where the operator's dirs are bind-mounted)
    // and `/home/op` on the host. Probing homeDir (the baked host path) inside
    // hostd finds nothing and drops every conditional mount (the 2026-06-15
    // marko meta_pages outage). On the host the two are identical.
    probeHomeDir: homedir(),
    switchroomConfigPath: resolvedConfigPath,
    // Captured for the broker's host-shell operator socket chown.
    operatorUid,
  });

  let previous: string | null = null;
  try {
    previous = await readFile(opts.composePath, "utf8");
  } catch {
    previous = null;
  }
  const previousImageTag = previous ? (AGENT_IMAGE_TAG_RE.exec(previous)?.[1] ?? null) : null;

  await mkdir(dirname(opts.composePath), { recursive: true });
  await writeFile(opts.composePath, content, { encoding: "utf8", mode: 0o600 });

  // Keep the compose operator-owned when written under sudo. `apply` also
  // does this via its whole-tree restoreOperatorOwnership sweep, but the
  // `agent restart` path doesn't run that sweep — without this, a root-mode
  // restart would leave the compose root-owned and lock the operator out of
  // non-sudo `docker compose` reads. Best-effort (dev/no CAP_CHOWN/raced).
  if (operatorUid !== undefined && process.geteuid?.() === 0) {
    try {
      chownSync(opts.composePath, operatorUid, operatorUid);
    } catch {
      /* best-effort — matches restoreOperatorOwnership's per-path tolerance */
    }
  }

  return {
    composePath: opts.composePath,
    imageTag,
    bytes: Buffer.byteLength(content, "utf8"),
    changed: previous !== content,
    previousImageTag,
  };
}
