import { execFileSync } from "node:child_process";
import { createServer } from "node:net";

/**
 * Default Hindsight ports (upstream defaults).
 */
export const HINDSIGHT_DEFAULT_API_PORT = 8888;
export const HINDSIGHT_DEFAULT_UI_PORT = 9999;

/**
 * Default cap on observations per *tag scope*.
 *
 * Upstream Hindsight defaults `HINDSIGHT_API_MAX_OBSERVATIONS_PER_SCOPE`
 * to `-1` (unlimited). Once a tag scope hits the cap, consolidation
 * stops creating new observations and only updates/deletes existing
 * ones — bounding the cost of consolidating a single long-running
 * scope. Tagless observations are unaffected.
 *
 * Switchroom retains with `retainTags: ["{session_id}"]` (vendored
 * plugin default), so a "tag scope" maps roughly to "one session." A
 * very long Telegram session that runs for weeks can accumulate
 * thousands of observations under one scope — that's the case 1000
 * targets. Most sessions are far below the cap, so for typical
 * agents this is defense-in-depth rather than an active limit.
 *
 * This is NOT a fix for vectorize-io/hindsight#1284 (the upstream
 * unbounded-growth bug for consolidation across a whole bank); it's a
 * companion safety rail until that lands. Operators who want a
 * different value can stop the container and re-run `docker run`
 * with `-e HINDSIGHT_API_MAX_OBSERVATIONS_PER_SCOPE=N`.
 */
export const HINDSIGHT_DEFAULT_MAX_OBSERVATIONS_PER_SCOPE = 1000;

/**
 * Default consumer slug for the hindsight broker socket. Path-as-identity
 * — the broker binds `/run/switchroom/auth-broker/<slug>/sock` and chowns
 * it to the configured UID. See `auth.consumers[]` in `src/config/schema.ts`
 * and RFC H §4.8.
 */
export const HINDSIGHT_CONSUMER_NAME = "hindsight";

/**
 * Default UID for the hindsight container's broker socket. The container
 * runs as the upstream `hindsight` user; we pick a fixed UID in the
 * consumer range (>10000, not colliding with switchroom agent UIDs at
 * 10001-10999) so the chowned socket is readable inside.
 *
 * Operators can override per-install via `auth.consumers[].uid` in
 * `switchroom.yaml`.
 */
export const HINDSIGHT_DEFAULT_UID = 11000;

/**
 * Docker image for switchroom's hindsight (extends upstream with the
 * `claude-code` LLM provider's runtime deps). Pulled from GHCR at apply
 * time; built from `docker/Dockerfile.hindsight` when `--build-local`.
 */
export const HINDSIGHT_IMAGE = "ghcr.io/switchroom/switchroom-hindsight:latest";

/**
 * Default Claude model for hindsight's LLM operations (retain / reflect /
 * consolidation — recall is local-only, no LLM). Matches the fleet-wide
 * `SWITCHROOM_DEFAULT_MAIN_MODEL` in `src/agents/scaffold.ts` so a fresh
 * deployment uses one consistent model across agents and memory.
 *
 * Upstream `vectorize-io/hindsight` defaults to a date-pinned older
 * sonnet (`claude-sonnet-4-5-20250929`) via PROVIDER_DEFAULT_MODELS in
 * /app/api/hindsight_api/config.py. Without this override the container
 * silently drifts behind the rest of switchroom on every upstream
 * hindsight pull. Pinning here keeps both surfaces in lockstep.
 *
 * Operators who need a different model can still override at runtime
 * via `docker run -e HINDSIGHT_API_LLM_MODEL=...` or by editing the
 * generated compose snippet.
 */
export const HINDSIGHT_DEFAULT_MODEL = "claude-sonnet-4-6";

/**
 * Run hindsight's MCP server in stateless HTTP mode.
 *
 * Upstream defaults to stateful (`HINDSIGHT_API_MCP_STATELESS=false`):
 * the server assigns an `Mcp-Session-Id` on the client's first
 * `initialize`, and every subsequent request must echo it back. That
 * mode is for clients that want SSE streaming / GET subscriptions —
 * neither of which switchroom uses; agent retain/recall are POST-only
 * tool calls with idempotent request/response semantics.
 *
 * Stateful mode has a sharp edge for our deploy model: bouncing the
 * hindsight container wipes its in-memory session registry, but every
 * agent's claude MCP client keeps caching the now-stale session id.
 * Every retain after the bounce errors with "Session not found" until
 * each agent is also restarted. Operationally this means a single
 * `switchroom memory --restart` silently breaks the fleet's retain
 * path. Stateless mode dodges the whole class of failures — every
 * request is self-contained, no session to invalidate.
 *
 * Operators with bespoke MCP clients that need streaming can flip
 * this back via `docker run -e HINDSIGHT_API_MCP_STATELESS=false`.
 */
export const HINDSIGHT_DEFAULT_MCP_STATELESS = true;

/**
 * Named volume that the auth-broker singleton chowns the hindsight
 * consumer socket into. Generated by `src/agents/compose.ts` from
 * `auth.consumers[].name`; mirrored here so the standalone `switchroom
 * memory --start` path (which doesn't go through compose) can bind it.
 */
export const HINDSIGHT_BROKER_SOCK_VOLUME = `auth-broker-${HINDSIGHT_CONSUMER_NAME}-sock`;

/**
 * Reranker smart-defaults (v0.13.22).
 *
 * The hindsight server's cross-encoder reranker is the single biggest
 * latency contributor on the recall path — 87% of p50 5.6s on the
 * 2026-05-24 fleet audit. Each of these knobs has a vendor default that
 * is sub-optimal for switchroom's workload (CPU-only, shared host,
 * Telegram-shaped concurrency); we override to the optimal value out of
 * the box so a fresh `switchroom setup` produces a fast hindsight
 * without any operator tuning.
 *
 * - BUCKET_BATCHING: vendor default `false`. Vendor's own config.py
 *   comment promises "36-54% speedup, quality-identical" by sorting
 *   candidate pairs by length to avoid padding waste. Pure win on CPU.
 *
 * - MAX_CANDIDATES: vendor default 300. At our `recallBudget=low`
 *   ~100 candidates feed in and we cap to 12 final memories; scoring
 *   300 wastes ~50% of rerank CPU on candidates that will never make
 *   the top-N.
 *
 * - LOCAL_MAX_CONCURRENT: vendor default 4. With 9 always-on agents
 *   that's up to 36 simultaneous CPU-bound rerank tasks on a shared
 *   16-core host — thrashes. Cap at 2 leaves headroom for burst.
 *
 * - RECALL_MAX_CONCURRENT: vendor default 32. Sized for a dedicated
 *   hindsight box; switchroom is co-tenant with the fleet, hostd,
 *   brokers, etc. 8 matches realistic concurrency without lock
 *   contention.
 *
 * All four are operator-overridable by editing the generated compose
 * snippet or the `docker run -e ...` flags — but they should never
 * NEED tuning for a single-host fleet install.
 */
export const HINDSIGHT_DEFAULT_RERANKER_BUCKET_BATCHING = "true";
export const HINDSIGHT_DEFAULT_RERANKER_MAX_CANDIDATES = 150;
// Vendor default 4. v0.13.22 dropped this to 2 paired with the now-
// reverted `--cpus=2.0` CPU cap; with CPU restored, 4-way concurrency
// is the right knob — lets 4 fleet agents' recalls overlap without
// thrashing per-pair compute (which is the actual bottleneck, not
// task-level contention).
export const HINDSIGHT_DEFAULT_RERANKER_LOCAL_MAX_CONCURRENT = 4;
export const HINDSIGHT_DEFAULT_RECALL_MAX_CONCURRENT = 8;

/**
 * Container resource caps (memory + pids only; CPU intentionally NOT capped).
 *
 * Live observed RSS on a 9-agent fleet: 3.4 GiB. Capping memory at
 * 4g prevents a runaway reranker batch from eating the host (which
 * is shared with Coolify on dev/canary boxes and would be shared
 * with the agent fleet on any single-host install). 2g soft
 * reservation protects the working set under host pressure.
 *
 * **CPU cap intentionally NOT set (v0.13.23).** v0.13.22 shipped
 * `--cpus=2.0` on the theory that bursts of concurrent rerank tasks
 * would starve the agent fleet. Live measurement immediately after
 * deploy showed the opposite: the cross-encoder rerank is dominated
 * by per-pair compute, not contention. Capping CPU at 2 cores
 * forced each rerank to serialize through 2 cores instead of using
 * whatever the host had free, which made each pass 3-10x SLOWER
 * (rerank p50 rose from ~4.9s pre-deploy → 7-20s post-deploy,
 * despite all the other smart-defaults staying in place). Removing
 * the cap restored ~2.1s reranks. Bursts are bounded by
 * `RERANKER_LOCAL_MAX_CONCURRENT` (restored to vendor default of 4)
 * — that's the right knob for fleet-fairness, not a wall-clock CPU
 * cap.
 *
 * PIDs cap is defense-in-depth, matches the agent `coding` profile.
 */
export const HINDSIGHT_DEFAULT_MEM_LIMIT = "4g";
export const HINDSIGHT_DEFAULT_MEM_RESERVATION = "2g";
export const HINDSIGHT_DEFAULT_PIDS_LIMIT = 1000;

/**
 * Check if a TCP port is free for binding on 127.0.0.1.
 * Returns true if free, false if something is already listening.
 */
export function isPortFree(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const server = createServer();
    server.once("error", () => resolve(false));
    server.once("listening", () => {
      server.close(() => resolve(true));
    });
    server.listen(port, "127.0.0.1");
  });
}

/**
 * Find a free port starting at `start`, incrementing until one is found
 * or `maxAttempts` ports have been tried.
 */
export async function findFreePort(
  start: number,
  maxAttempts = 50,
): Promise<number | null> {
  for (let i = 0; i < maxAttempts; i++) {
    const port = start + i;
    if (port < 1024) continue;
    if (await isPortFree(port)) {
      return port;
    }
  }
  return null;
}

/**
 * Pick host ports for the Hindsight container.
 */
export async function pickHindsightPorts(): Promise<{
  apiPort: number;
  uiPort: number;
}> {
  if (
    (await isPortFree(HINDSIGHT_DEFAULT_API_PORT)) &&
    (await isPortFree(HINDSIGHT_DEFAULT_UI_PORT))
  ) {
    return {
      apiPort: HINDSIGHT_DEFAULT_API_PORT,
      uiPort: HINDSIGHT_DEFAULT_UI_PORT,
    };
  }
  const apiPort = await findFreePort(18888);
  const uiPort = await findFreePort(19999);
  if (apiPort === null || uiPort === null) {
    throw new Error(
      "Could not find a free port for Hindsight. " +
        "Stop whatever is using 8888 / 9999 / 18888 / 19999 and retry.",
    );
  }
  return { apiPort, uiPort };
}

/**
 * Check if Docker is available on the system.
 */
export function isDockerAvailable(): boolean {
  try {
    execFileSync("docker", ["--version"], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if the switchroom-hindsight container is currently running.
 */
export function isHindsightRunning(): boolean {
  try {
    const output = execFileSync(
      "docker",
      ["ps", "--filter", "name=switchroom-hindsight", "--format", "{{.Status}}"],
      { stdio: "pipe", encoding: "utf-8" },
    );
    return output.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * Check if the switchroom-hindsight container exists (running or stopped).
 */
export function isHindsightContainerExists(): boolean {
  try {
    const output = execFileSync(
      "docker",
      ["ps", "-a", "--filter", "name=switchroom-hindsight", "--format", "{{.Names}}"],
      { stdio: "pipe", encoding: "utf-8" },
    );
    return output.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * Start the Hindsight Docker container in **broker-fed** mode (RFC H §4.8).
 *
 * Hindsight uses the upstream `claude-code` LLM provider, which routes
 * consolidation/recall through the user's Claude Pro/Max subscription
 * via `claude_agent_sdk.query()`. No OpenAI / Anthropic API key is
 * required — credentials are fetched at boot from the auth-broker over
 * the per-consumer UDS bind-mounted as the named volume
 * `auth-broker-hindsight-sock` (chowned by the broker to the consumer
 * UID, see `auth.consumers[]` in switchroom.yaml).
 *
 * @param ports - Optional host port mapping. If omitted, tries upstream
 *   defaults (8888/9999) then 18888/19999.
 */
export function startHindsight(ports?: { apiPort: number; uiPort: number }): void {
  const apiPort = ports?.apiPort ?? HINDSIGHT_DEFAULT_API_PORT;
  const uiPort = ports?.uiPort ?? HINDSIGHT_DEFAULT_UI_PORT;

  // Non-secret env stays on `-e` — provider name + observation cap are
  // configuration, not secrets. Setting `HINDSIGHT_API_LLM_PROVIDER` to
  // `claude-code` selects the subscription-honest path; pinning
  // `HINDSIGHT_API_LLM_MODEL` keeps memory ops on the same Claude model
  // the agent fleet uses (see HINDSIGHT_DEFAULT_MODEL above).
  const envArgs: string[] = [
    "-e", `HINDSIGHT_API_MAX_OBSERVATIONS_PER_SCOPE=${HINDSIGHT_DEFAULT_MAX_OBSERVATIONS_PER_SCOPE}`,
    "-e", "HINDSIGHT_API_LLM_PROVIDER=claude-code",
    "-e", `HINDSIGHT_API_LLM_MODEL=${HINDSIGHT_DEFAULT_MODEL}`,
    "-e", `HINDSIGHT_API_MCP_STATELESS=${HINDSIGHT_DEFAULT_MCP_STATELESS}`,
    // Reranker smart-defaults (v0.13.22) — see constants above for
    // rationale. Each closes a vendor-default gap that hurts our
    // CPU-only / shared-host / Telegram workload.
    "-e", `HINDSIGHT_API_RERANKER_LOCAL_BUCKET_BATCHING=${HINDSIGHT_DEFAULT_RERANKER_BUCKET_BATCHING}`,
    "-e", `HINDSIGHT_API_RERANKER_MAX_CANDIDATES=${HINDSIGHT_DEFAULT_RERANKER_MAX_CANDIDATES}`,
    "-e", `HINDSIGHT_API_RERANKER_LOCAL_MAX_CONCURRENT=${HINDSIGHT_DEFAULT_RERANKER_LOCAL_MAX_CONCURRENT}`,
    "-e", `HINDSIGHT_API_RECALL_MAX_CONCURRENT=${HINDSIGHT_DEFAULT_RECALL_MAX_CONCURRENT}`,
  ];

  const args = [
    "run", "-d",
    "--name", "switchroom-hindsight",
    "--restart", "unless-stopped",
    // Container resource caps (memory + pids only; CPU uncapped —
    // see HINDSIGHT_DEFAULT_MEM_LIMIT constant for the v0.13.22 → v0.13.23
    // unwind rationale).
    `--memory=${HINDSIGHT_DEFAULT_MEM_LIMIT}`,
    `--memory-reservation=${HINDSIGHT_DEFAULT_MEM_RESERVATION}`,
    `--pids-limit=${HINDSIGHT_DEFAULT_PIDS_LIMIT}`,
    "-p", `127.0.0.1:${apiPort}:8888`,
    "-p", `127.0.0.1:${uiPort}:9999`,
    "-v", "switchroom-hindsight-data:/home/hindsight/.pg0",
    // Broker UDS — same shape the agent fleet uses. The named volume is
    // populated by the auth-broker singleton (which chowns the socket to
    // the declared consumer UID); inside this container the socket is
    // visible at /run/switchroom/auth-broker/sock.
    "-v", `${HINDSIGHT_BROKER_SOCK_VOLUME}:/run/switchroom/auth-broker`,
    // Tmpfs for the dotfile written by the entrypoint shim. Lives in RAM
    // only — the broker remains the single writer of OAuth state on disk.
    // `uid=` + `gid=` are required because the image's `USER hindsight`
    // (UID 11000, pinned in Dockerfile.hindsight) runs the entrypoint;
    // without explicit ownership, tmpfs mounts root-owned and the
    // entrypoint's `chmod 0700` fails EACCES → restart-loop.
    "--tmpfs", `/run/claude-creds:rw,mode=0700,uid=${HINDSIGHT_DEFAULT_UID},gid=${HINDSIGHT_DEFAULT_UID}`,
    ...envArgs,
    HINDSIGHT_IMAGE,
  ];

  execFileSync("docker", args, { stdio: "pipe" });
}

/**
 * Stop and remove the Hindsight Docker container.
 */
export function stopHindsight(): void {
  try {
    execFileSync("docker", ["stop", "switchroom-hindsight"], { stdio: "pipe" });
  } catch { /* container may already be stopped */ }
  try {
    execFileSync("docker", ["rm", "switchroom-hindsight"], { stdio: "pipe" });
  } catch { /* container may already be removed */ }
}

/**
 * Get the status of the Hindsight Docker container.
 */
export function getHindsightStatus(): string | null {
  try {
    const output = execFileSync(
      "docker",
      ["ps", "-a", "--filter", "name=switchroom-hindsight", "--format", "{{.Status}}"],
      { stdio: "pipe", encoding: "utf-8" },
    );
    const status = output.trim();
    return status.length > 0 ? status : null;
  } catch {
    return null;
  }
}

/**
 * Get the MCP server config for Hindsight via HTTP endpoint.
 * Hindsight exposes MCP via Streamable HTTP at localhost:8888/mcp.
 */
export function getHindsightMcpUrl(): {
  url: string;
} {
  return {
    url: "http://localhost:8888/mcp/",
  };
}

/**
 * Generate a docker-compose snippet for Hindsight in broker-fed mode.
 * Bind-mounts the auth-broker consumer socket volume and tmpfs for
 * the credential dotfile; no LLM API key is needed.
 *
 * The named volume `auth-broker-hindsight-sock` must be `external: true`
 * because it's owned by the switchroom compose project (the auth-broker
 * container chowns and binds the per-consumer socket inside it). The
 * hindsight compose project is separate; it consumes the volume.
 */
export function generateHindsightComposeSnippet(): string {
  return [
    "services:",
    "  switchroom-hindsight:",
    `    image: ${HINDSIGHT_IMAGE}`,
    "    container_name: switchroom-hindsight",
    "    ports:",
    "      - \"8888:8888\"",
    "      - \"9999:9999\"",
    "    environment:",
    `      - HINDSIGHT_API_MAX_OBSERVATIONS_PER_SCOPE=${HINDSIGHT_DEFAULT_MAX_OBSERVATIONS_PER_SCOPE}`,
    "      - HINDSIGHT_API_LLM_PROVIDER=claude-code",
    `      - HINDSIGHT_API_LLM_MODEL=${HINDSIGHT_DEFAULT_MODEL}`,
    `      - HINDSIGHT_API_MCP_STATELESS=${HINDSIGHT_DEFAULT_MCP_STATELESS}`,
    `      - HINDSIGHT_API_RERANKER_LOCAL_BUCKET_BATCHING=${HINDSIGHT_DEFAULT_RERANKER_BUCKET_BATCHING}`,
    `      - HINDSIGHT_API_RERANKER_MAX_CANDIDATES=${HINDSIGHT_DEFAULT_RERANKER_MAX_CANDIDATES}`,
    `      - HINDSIGHT_API_RERANKER_LOCAL_MAX_CONCURRENT=${HINDSIGHT_DEFAULT_RERANKER_LOCAL_MAX_CONCURRENT}`,
    `      - HINDSIGHT_API_RECALL_MAX_CONCURRENT=${HINDSIGHT_DEFAULT_RECALL_MAX_CONCURRENT}`,
    `    mem_limit: ${HINDSIGHT_DEFAULT_MEM_LIMIT}`,
    `    mem_reservation: ${HINDSIGHT_DEFAULT_MEM_RESERVATION}`,
    `    pids_limit: ${HINDSIGHT_DEFAULT_PIDS_LIMIT}`,
    "    volumes:",
    "      - switchroom-hindsight-data:/home/hindsight/.pg0",
    `      - ${HINDSIGHT_BROKER_SOCK_VOLUME}:/run/switchroom/auth-broker`,
    "    tmpfs:",
    `      - /run/claude-creds:rw,mode=0700,uid=${HINDSIGHT_DEFAULT_UID},gid=${HINDSIGHT_DEFAULT_UID}`,
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  switchroom-hindsight-data:",
    `  ${HINDSIGHT_BROKER_SOCK_VOLUME}:`,
    "    external: true",
    "    # Bound by the switchroom-auth-broker singleton in the main",
    "    # switchroom compose project. Declare an `auth.consumers[]`",
    `    # entry named "${HINDSIGHT_CONSUMER_NAME}" in switchroom.yaml.`,
  ].join("\n");
}

/**
 * Edit `switchroom.yaml` in place to ensure an `auth.consumers[]` entry
 * exists for the hindsight container. Idempotent: if an entry with the
 * same `name` is already present, leaves it untouched.
 *
 * @param configPath  absolute path to switchroom.yaml
 * @param account     account label to pin the consumer to (typically
 *                    `auth.active` at setup time)
 * @param uid         UID to chown the consumer socket to;
 *                    defaults to HINDSIGHT_DEFAULT_UID
 */
export async function ensureHindsightConsumer(
  configPath: string,
  account: string,
  uid: number = HINDSIGHT_DEFAULT_UID,
): Promise<{ added: boolean; reason: string }> {
  const fs = await import("node:fs");
  const { parseDocument, isMap, isSeq, YAMLMap, YAMLSeq } = await import("yaml");
  const { atomicWriteFileSync } = await import("../util/atomic.js");

  const raw = fs.readFileSync(configPath, "utf-8");
  const doc = parseDocument(raw);
  const root = doc.contents;
  if (!isMap(root)) {
    return { added: false, reason: "switchroom.yaml root is not a map" };
  }

  // Ensure auth: { ... } exists as a map.
  const authRaw = root.get("auth", true);
  let authNode: InstanceType<typeof YAMLMap>;
  if (isMap(authRaw)) {
    authNode = authRaw as InstanceType<typeof YAMLMap>;
  } else {
    authNode = new YAMLMap();
    doc.setIn(["auth"], authNode);
  }

  // Ensure auth.consumers: [...] exists as a sequence.
  const consumersRaw = authNode.get("consumers", true);
  let consumersNode: InstanceType<typeof YAMLSeq>;
  if (isSeq(consumersRaw)) {
    consumersNode = consumersRaw as InstanceType<typeof YAMLSeq>;
  } else {
    consumersNode = new YAMLSeq();
    doc.setIn(["auth", "consumers"], consumersNode);
  }

  // Idempotency: leave any existing entry with the same name alone.
  for (const item of consumersNode.items) {
    if (isMap(item)) {
      const name = item.get("name");
      if (name === HINDSIGHT_CONSUMER_NAME) {
        return { added: false, reason: "already present" };
      }
    }
  }

  const entry = new YAMLMap();
  entry.set("name", HINDSIGHT_CONSUMER_NAME);
  entry.set("account", account);
  entry.set("uid", uid);
  consumersNode.add(entry);

  const out = String(doc);
  const tail = out.endsWith("\n") ? out : out + "\n";
  let mode = 0o644;
  try { mode = fs.statSync(configPath).mode & 0o777; } catch { /* default */ }
  atomicWriteFileSync(configPath, tail, mode);
  return { added: true, reason: "added" };
}
