/**
 * A REAL healthy-fleet sample, captured from the live logs on 2026-07-27.
 *
 * This file exists because the fixture it replaces was the subject of a
 * review finding, and the finding was correct. The old `healthyRows()` built
 * every row with `elapsedMs: 1100` and a constant score of 0.31, then
 * asserted "recall signals stay silent on a healthy fleet". Against those
 * numbers ANY threshold in the drafted range stays silent, so the test
 * validated threshold DIRECTION while its name claimed threshold SAFETY —
 * and safety is this change's central claim. It could not have caught either
 * of the two mis-set lines that review found (a recall-latency page line
 * below the healthy median, and an injected-score warn line at the healthy
 * p50), because both are properties of the healthy distribution's TAILS and
 * the fixture had no tails.
 *
 * So the fixture is now the distribution itself. Every row here is a real
 * recall that SUCCEEDED — the conditioning predicate is "no bank timed out,
 * errored, or hit the shared deadline", which is the best available proxy for
 * a fleet whose recall has been repaired. n=183 across 9 agents.
 *
 * Measured properties of this sample, which the tests assert against:
 *
 *   wall time    p50 6420 ms   p90 7935 ms   p95 8037 ms   max 11859 ms
 *   injected     p10 0.0005  p50 0.0850  p90 0.9259   (n=74 scored)
 *   pool         p10 10      p50 41      min 3
 *   zero-memory  28/183 = 15.3 %
 *
 * The latency figures are why `recall-latency` is not a signal: this p95 sits
 * at the 8 s per-bank wall it was captured under, RIGHT-CENSORED there. #3759
 * later moved the wall to a 10 s declarative envelope, but a censored 8 s
 * sample cannot describe the 8-10 s band, so the band is still not
 * thresholdable — see the deletion note in `thresholds.ts` (RECALL_WALL_MS).
 * The score p10 is why the injected-score warn moved from 0.05 to 0.02.
 *
 * Content: numeric telemetry only. Bank ids are remapped to `agent-NN` /
 * `side-NN` — no query text, no memory content, and no agent identity is
 * carried here. The remap preserves the STRUCTURE the reducer depends on
 * (the own bank is matched by id, and is not always at index 0).
 *
 * Regenerating: re-run the capture against the live logs once recall is
 * repaired, and re-derive the thresholds from the new distribution rather
 * than editing constants to keep this file green.
 *
 * @generated captured 2026-07-27 — see CHANGELOG "arm the watchdog"
 */

export interface HealthyFixtureRow {
  agent: string;
  bank_id: string;
  result_count: number | null;
  total_elapsed_ms: number | null;
  pre_cap_count: number | null;
  overlap_dropped: number | null;
  injected_score_max: number | null;
  bank_timings: Array<{
    bank_id: string;
    elapsed_ms: number | null;
    timed_out: boolean;
    errored: boolean;
  }>;
}

export const HEALTHY_FLEET_ROWS: HealthyFixtureRow[] = [
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 0,
    total_elapsed_ms: 6001,
    pre_cap_count: 0,
    overlap_dropped: 50,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 5999,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3838,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 0,
    total_elapsed_ms: 6924,
    pre_cap_count: 0,
    overlap_dropped: 39,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 6921,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2339,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 4,
    total_elapsed_ms: 7833,
    pre_cap_count: 4,
    overlap_dropped: 48,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 7827,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 4403,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 6,
    total_elapsed_ms: 7187,
    pre_cap_count: 6,
    overlap_dropped: 48,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 7182,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2752,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 2,
    total_elapsed_ms: 4709,
    pre_cap_count: 2,
    overlap_dropped: 51,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 4707,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1775,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 1,
    total_elapsed_ms: 4980,
    pre_cap_count: 1,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 4978,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1480,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 1,
    total_elapsed_ms: 6792,
    pre_cap_count: 1,
    overlap_dropped: 20,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 6788,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 3,
    total_elapsed_ms: 7836,
    pre_cap_count: 3,
    overlap_dropped: 50,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 7831,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2698,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 1,
    total_elapsed_ms: 6773,
    pre_cap_count: 1,
    overlap_dropped: 40,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 6768,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2468,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 4,
    total_elapsed_ms: 5048,
    pre_cap_count: 4,
    overlap_dropped: 50,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 5046,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1229,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 2,
    total_elapsed_ms: 6669,
    pre_cap_count: 2,
    overlap_dropped: 6,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 6666,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 4,
    total_elapsed_ms: 7490,
    pre_cap_count: 4,
    overlap_dropped: 4,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 7486,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 3,
    total_elapsed_ms: 6890,
    pre_cap_count: 3,
    overlap_dropped: 5,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 6888,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 0,
    total_elapsed_ms: 5981,
    pre_cap_count: 0,
    overlap_dropped: 47,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 5979,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1714,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 2,
    total_elapsed_ms: 4642,
    pre_cap_count: 2,
    overlap_dropped: 50,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 4639,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1606,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 0,
    total_elapsed_ms: 3694,
    pre_cap_count: 0,
    overlap_dropped: 45,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 3693,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1768,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 6,
    total_elapsed_ms: 7888,
    pre_cap_count: 6,
    overlap_dropped: 10,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 7886,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 6,
    total_elapsed_ms: 5032,
    pre_cap_count: 11,
    overlap_dropped: 37,
    injected_score_max: 0.9834,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 5030,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1384,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-01",
    bank_id: "agent-01",
    result_count: 6,
    total_elapsed_ms: 6581,
    pre_cap_count: 9,
    overlap_dropped: 32,
    injected_score_max: 0.0024,
    bank_timings: [
      {
        bank_id: "agent-01",
        elapsed_ms: 6578,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 474,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-02",
    bank_id: "agent-02",
    result_count: 6,
    total_elapsed_ms: 7934,
    pre_cap_count: 24,
    overlap_dropped: 30,
    injected_score_max: 0.0016,
    bank_timings: [
      {
        bank_id: "agent-02",
        elapsed_ms: 7928,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 212,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 206,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-02",
    bank_id: "agent-02",
    result_count: 6,
    total_elapsed_ms: 6916,
    pre_cap_count: 23,
    overlap_dropped: 41,
    injected_score_max: 0.0066,
    bank_timings: [
      {
        bank_id: "agent-02",
        elapsed_ms: 6909,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 587,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 589,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-02",
    bank_id: "agent-02",
    result_count: 6,
    total_elapsed_ms: 7466,
    pre_cap_count: 6,
    overlap_dropped: 25,
    injected_score_max: 0.0924,
    bank_timings: [
      {
        bank_id: "agent-02",
        elapsed_ms: 7461,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 368,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-02",
    bank_id: "agent-02",
    result_count: 6,
    total_elapsed_ms: 7431,
    pre_cap_count: 6,
    overlap_dropped: 23,
    injected_score_max: 0.0459,
    bank_timings: [
      {
        bank_id: "agent-02",
        elapsed_ms: 7425,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 378,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-02",
    bank_id: "agent-02",
    result_count: 6,
    total_elapsed_ms: 7854,
    pre_cap_count: 8,
    overlap_dropped: 26,
    injected_score_max: 0.0046,
    bank_timings: [
      {
        bank_id: "agent-02",
        elapsed_ms: 7847,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 971,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-02",
    bank_id: "agent-02",
    result_count: 6,
    total_elapsed_ms: 5030,
    pre_cap_count: 16,
    overlap_dropped: 53,
    injected_score_max: 0.5809,
    bank_timings: [
      {
        bank_id: "agent-02",
        elapsed_ms: 5023,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 527,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 527,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 5,
    total_elapsed_ms: 4524,
    pre_cap_count: 5,
    overlap_dropped: 53,
    injected_score_max: 0.159,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 4522,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1593,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 6,
    total_elapsed_ms: 9181,
    pre_cap_count: 36,
    overlap_dropped: 26,
    injected_score_max: 0.9582,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 9173,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2826,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 6,
    total_elapsed_ms: 3342,
    pre_cap_count: 8,
    overlap_dropped: 45,
    injected_score_max: 0.9014,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 3340,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1283,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 6,
    total_elapsed_ms: 2807,
    pre_cap_count: 21,
    overlap_dropped: 43,
    injected_score_max: 0.7523,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 2805,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1514,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 6,
    total_elapsed_ms: 2083,
    pre_cap_count: 27,
    overlap_dropped: 34,
    injected_score_max: 1.0003,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 2081,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 413,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 3,
    total_elapsed_ms: 7935,
    pre_cap_count: 3,
    overlap_dropped: 0,
    injected_score_max: 0.419,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 7933,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 6,
    total_elapsed_ms: 4321,
    pre_cap_count: 23,
    overlap_dropped: 17,
    injected_score_max: 0.9213,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 4314,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 428,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-03",
    bank_id: "agent-03",
    result_count: 6,
    total_elapsed_ms: 6663,
    pre_cap_count: 22,
    overlap_dropped: 15,
    injected_score_max: 0.1384,
    bank_timings: [
      {
        bank_id: "agent-03",
        elapsed_ms: 6658,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 539,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 5619,
    pre_cap_count: 23,
    overlap_dropped: 51,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 5615,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3494,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 5282,
    pre_cap_count: 29,
    overlap_dropped: 53,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 5277,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3563,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 5367,
    pre_cap_count: 28,
    overlap_dropped: 43,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 5363,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3718,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 2,
    total_elapsed_ms: 7319,
    pre_cap_count: 2,
    overlap_dropped: 44,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7314,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 4566,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 2,
    total_elapsed_ms: 7872,
    pre_cap_count: 2,
    overlap_dropped: 8,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7869,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 3202,
    pre_cap_count: 15,
    overlap_dropped: 33,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3200,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1617,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 5421,
    pre_cap_count: 21,
    overlap_dropped: 61,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 5416,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3496,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 6555,
    pre_cap_count: 18,
    overlap_dropped: 51,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 6551,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3917,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 1,
    total_elapsed_ms: 7859,
    pre_cap_count: 1,
    overlap_dropped: 41,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7854,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 4345,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 0,
    total_elapsed_ms: 3922,
    pre_cap_count: 0,
    overlap_dropped: 42,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3920,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2173,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 1,
    total_elapsed_ms: 4606,
    pre_cap_count: 1,
    overlap_dropped: 18,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 4604,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 3,
    total_elapsed_ms: 7909,
    pre_cap_count: 3,
    overlap_dropped: 11,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7852,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 0,
    total_elapsed_ms: 6535,
    pre_cap_count: 0,
    overlap_dropped: 3,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 6532,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 5,
    total_elapsed_ms: 3022,
    pre_cap_count: 5,
    overlap_dropped: 42,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3020,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1479,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 5,
    total_elapsed_ms: 7981,
    pre_cap_count: 5,
    overlap_dropped: 5,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7936,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 2,
    total_elapsed_ms: 7728,
    pre_cap_count: 2,
    overlap_dropped: 42,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7723,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3589,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 3,
    total_elapsed_ms: 6034,
    pre_cap_count: 3,
    overlap_dropped: 2,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 6030,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 4,
    total_elapsed_ms: 7898,
    pre_cap_count: 4,
    overlap_dropped: 6,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7893,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 7732,
    pre_cap_count: 6,
    overlap_dropped: 9,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7728,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 3,
    total_elapsed_ms: 5732,
    pre_cap_count: 3,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 5726,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3261,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 0,
    total_elapsed_ms: 7362,
    pre_cap_count: 0,
    overlap_dropped: 44,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7353,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 4116,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 3,
    total_elapsed_ms: 7559,
    pre_cap_count: 3,
    overlap_dropped: 5,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7558,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 2,
    total_elapsed_ms: 7254,
    pre_cap_count: 2,
    overlap_dropped: 41,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7248,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3714,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 3,
    total_elapsed_ms: 7519,
    pre_cap_count: 3,
    overlap_dropped: 4,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7518,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 0,
    total_elapsed_ms: 7767,
    pre_cap_count: 0,
    overlap_dropped: 46,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7762,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3059,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 2,
    total_elapsed_ms: 7600,
    pre_cap_count: 2,
    overlap_dropped: 38,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7561,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3678,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 2,
    total_elapsed_ms: 7099,
    pre_cap_count: 2,
    overlap_dropped: 43,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7093,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3524,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 3110,
    pre_cap_count: 6,
    overlap_dropped: 41,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3109,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1676,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 1,
    total_elapsed_ms: 3511,
    pre_cap_count: 1,
    overlap_dropped: 38,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3510,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1815,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 4,
    total_elapsed_ms: 3300,
    pre_cap_count: 4,
    overlap_dropped: 40,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3299,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1560,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 3,
    total_elapsed_ms: 5679,
    pre_cap_count: 3,
    overlap_dropped: 46,
    injected_score_max: 0.033,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 5677,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2062,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 7055,
    pre_cap_count: 34,
    overlap_dropped: 32,
    injected_score_max: 0.9408,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 7050,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 4047,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 1142,
    pre_cap_count: 18,
    overlap_dropped: 42,
    injected_score_max: 0.3336,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 1140,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 484,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 3498,
    pre_cap_count: 11,
    overlap_dropped: 30,
    injected_score_max: 0.4738,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3494,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 218,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 2585,
    pre_cap_count: 21,
    overlap_dropped: 22,
    injected_score_max: 0.0194,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 2580,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 227,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-04",
    bank_id: "agent-04",
    result_count: 6,
    total_elapsed_ms: 3987,
    pre_cap_count: 26,
    overlap_dropped: 16,
    injected_score_max: 0.2221,
    bank_timings: [
      {
        bank_id: "agent-04",
        elapsed_ms: 3980,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 225,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 4,
    total_elapsed_ms: 6058,
    pre_cap_count: 4,
    overlap_dropped: 39,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 6056,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 5293,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 6,
    total_elapsed_ms: 5242,
    pre_cap_count: 7,
    overlap_dropped: 46,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 5237,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1987,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 0,
    total_elapsed_ms: 7675,
    pre_cap_count: 0,
    overlap_dropped: 47,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 7673,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1542,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 1,
    total_elapsed_ms: 5974,
    pre_cap_count: 1,
    overlap_dropped: 51,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 5971,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2349,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 1,
    total_elapsed_ms: 4971,
    pre_cap_count: 1,
    overlap_dropped: 49,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 4970,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1350,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 0,
    total_elapsed_ms: 3484,
    pre_cap_count: 0,
    overlap_dropped: 33,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 3483,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1613,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 6,
    total_elapsed_ms: 2810,
    pre_cap_count: 22,
    overlap_dropped: 39,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 2809,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1475,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 6,
    total_elapsed_ms: 7043,
    pre_cap_count: 7,
    overlap_dropped: 47,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 7037,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1829,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 1,
    total_elapsed_ms: 4995,
    pre_cap_count: 1,
    overlap_dropped: 51,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 4992,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1550,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 3,
    total_elapsed_ms: 6094,
    pre_cap_count: 3,
    overlap_dropped: 49,
    injected_score_max: 0.0226,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 6092,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1931,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 6,
    total_elapsed_ms: 10130,
    pre_cap_count: 7,
    overlap_dropped: 40,
    injected_score_max: 0.4122,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 10125,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2228,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 1,
    total_elapsed_ms: 4428,
    pre_cap_count: 1,
    overlap_dropped: 56,
    injected_score_max: 0.0005,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 4426,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2679,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 1,
    total_elapsed_ms: 3692,
    pre_cap_count: 1,
    overlap_dropped: 40,
    injected_score_max: 0.0002,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 3689,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1731,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 3,
    total_elapsed_ms: 3924,
    pre_cap_count: 3,
    overlap_dropped: 37,
    injected_score_max: 0.0955,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 3923,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1344,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-05",
    bank_id: "agent-05",
    result_count: 6,
    total_elapsed_ms: 5648,
    pre_cap_count: 7,
    overlap_dropped: 33,
    injected_score_max: 0.2196,
    bank_timings: [
      {
        bank_id: "agent-05",
        elapsed_ms: 5643,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 293,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 1,
    total_elapsed_ms: 7407,
    pre_cap_count: 1,
    overlap_dropped: 45,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7402,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3412,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7677,
    pre_cap_count: 18,
    overlap_dropped: 39,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7670,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5292,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7549,
    pre_cap_count: 0,
    overlap_dropped: 49,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7545,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3059,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 5990,
    pre_cap_count: 19,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5985,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2818,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7566,
    pre_cap_count: 15,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7559,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3432,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7771,
    pre_cap_count: 19,
    overlap_dropped: 36,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7764,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5783,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 6251,
    pre_cap_count: 0,
    overlap_dropped: 50,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6246,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2549,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7251,
    pre_cap_count: 0,
    overlap_dropped: 41,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7245,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3023,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6058,
    pre_cap_count: 15,
    overlap_dropped: 42,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6052,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3157,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 8037,
    pre_cap_count: 15,
    overlap_dropped: 36,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 8031,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3565,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 3575,
    pre_cap_count: 0,
    overlap_dropped: 47,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 3571,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2019,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 5926,
    pre_cap_count: 18,
    overlap_dropped: 42,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5920,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2930,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6080,
    pre_cap_count: 8,
    overlap_dropped: 6,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6078,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 5,
    total_elapsed_ms: 7946,
    pre_cap_count: 5,
    overlap_dropped: 49,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7941,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3795,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 2,
    total_elapsed_ms: 7927,
    pre_cap_count: 2,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7922,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2477,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7592,
    pre_cap_count: 0,
    overlap_dropped: 38,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7587,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3146,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 3,
    total_elapsed_ms: 3419,
    pre_cap_count: 3,
    overlap_dropped: 40,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 3417,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1328,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 3,
    total_elapsed_ms: 7972,
    pre_cap_count: 3,
    overlap_dropped: 32,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7965,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3197,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7991,
    pre_cap_count: 0,
    overlap_dropped: 39,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7978,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3451,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7241,
    pre_cap_count: 6,
    overlap_dropped: 5,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7239,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 1,
    total_elapsed_ms: 3839,
    pre_cap_count: 1,
    overlap_dropped: 35,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 3837,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 1695,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 6934,
    pre_cap_count: 0,
    overlap_dropped: 30,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6930,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3551,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7048,
    pre_cap_count: 0,
    overlap_dropped: 31,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7044,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2783,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7858,
    pre_cap_count: 0,
    overlap_dropped: 35,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7854,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3539,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 5,
    total_elapsed_ms: 4362,
    pre_cap_count: 5,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4360,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 1341,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7900,
    pre_cap_count: 0,
    overlap_dropped: 35,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7896,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3584,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 1,
    total_elapsed_ms: 2974,
    pre_cap_count: 1,
    overlap_dropped: 36,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 2973,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1304,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 5191,
    pre_cap_count: 0,
    overlap_dropped: 34,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5190,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 1903,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7335,
    pre_cap_count: 0,
    overlap_dropped: 36,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7331,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2928,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7996,
    pre_cap_count: 0,
    overlap_dropped: 29,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7992,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2748,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 7229,
    pre_cap_count: 0,
    overlap_dropped: 37,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7223,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2455,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 2,
    total_elapsed_ms: 8005,
    pre_cap_count: 2,
    overlap_dropped: 30,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 8002,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 3107,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6588,
    pre_cap_count: 8,
    overlap_dropped: 34,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6582,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2373,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 3,
    total_elapsed_ms: 7745,
    pre_cap_count: 3,
    overlap_dropped: 31,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7741,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2632,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7363,
    pre_cap_count: 8,
    overlap_dropped: 39,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7356,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3049,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 4,
    total_elapsed_ms: 7656,
    pre_cap_count: 4,
    overlap_dropped: 43,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7650,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2879,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6915,
    pre_cap_count: 7,
    overlap_dropped: 31,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6910,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3036,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7034,
    pre_cap_count: 9,
    overlap_dropped: 5,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7032,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 0,
    total_elapsed_ms: 8015,
    pre_cap_count: 0,
    overlap_dropped: 27,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 8012,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2931,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 7947,
    pre_cap_count: 6,
    overlap_dropped: 0,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7942,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 3,
    total_elapsed_ms: 6792,
    pre_cap_count: 3,
    overlap_dropped: 30,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6787,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2534,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 2,
    total_elapsed_ms: 7642,
    pre_cap_count: 2,
    overlap_dropped: 31,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 7636,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 2802,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 2,
    total_elapsed_ms: 5373,
    pre_cap_count: 2,
    overlap_dropped: 38,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5371,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 1655,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 8585,
    pre_cap_count: 17,
    overlap_dropped: 18,
    injected_score_max: 0.9925,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 8579,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3153,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 8134,
    pre_cap_count: 10,
    overlap_dropped: 33,
    injected_score_max: 0.0141,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 8128,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3476,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6759,
    pre_cap_count: 25,
    overlap_dropped: 39,
    injected_score_max: 0.7076,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6754,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3005,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 10959,
    pre_cap_count: 18,
    overlap_dropped: 17,
    injected_score_max: 0.3636,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 10953,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3989,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 3,
    total_elapsed_ms: 3419,
    pre_cap_count: 3,
    overlap_dropped: 50,
    injected_score_max: 0.0333,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 3418,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1387,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6641,
    pre_cap_count: 11,
    overlap_dropped: 19,
    injected_score_max: 0.0006,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6636,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 183,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 5578,
    pre_cap_count: 20,
    overlap_dropped: 6,
    injected_score_max: 0.0293,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5569,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 521,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 5393,
    pre_cap_count: 23,
    overlap_dropped: 10,
    injected_score_max: 0.0042,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5389,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 412,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 4168,
    pre_cap_count: 7,
    overlap_dropped: 24,
    injected_score_max: 0.003,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4162,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 544,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 4718,
    pre_cap_count: 12,
    overlap_dropped: 18,
    injected_score_max: 0.0001,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4712,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 329,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6637,
    pre_cap_count: 21,
    overlap_dropped: 12,
    injected_score_max: 0.085,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6632,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 399,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 4393,
    pre_cap_count: 34,
    overlap_dropped: 11,
    injected_score_max: 0.0182,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4387,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 361,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 5,
    total_elapsed_ms: 4248,
    pre_cap_count: 5,
    overlap_dropped: 27,
    injected_score_max: 0.0018,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4244,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 904,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 1,
    total_elapsed_ms: 6291,
    pre_cap_count: 1,
    overlap_dropped: 26,
    injected_score_max: 0.0001,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6284,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 431,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 4835,
    pre_cap_count: 7,
    overlap_dropped: 26,
    injected_score_max: 0.0021,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4830,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 1151,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 3518,
    pre_cap_count: 12,
    overlap_dropped: 25,
    injected_score_max: 0.0035,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 3513,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 183,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 5314,
    pre_cap_count: 10,
    overlap_dropped: 19,
    injected_score_max: 0.0016,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5309,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 660,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6265,
    pre_cap_count: 6,
    overlap_dropped: 0,
    injected_score_max: 0.8288,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6262,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 5,
    total_elapsed_ms: 6727,
    pre_cap_count: 5,
    overlap_dropped: 0,
    injected_score_max: 0.9259,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6724,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6483,
    pre_cap_count: 6,
    overlap_dropped: 18,
    injected_score_max: 0.045,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6476,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 657,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 4007,
    pre_cap_count: 9,
    overlap_dropped: 22,
    injected_score_max: 0.0124,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 4001,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 446,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 5739,
    pre_cap_count: 17,
    overlap_dropped: 12,
    injected_score_max: 0.1133,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 5734,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 466,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-06",
    bank_id: "agent-06",
    result_count: 6,
    total_elapsed_ms: 6420,
    pre_cap_count: 20,
    overlap_dropped: 13,
    injected_score_max: 0.1027,
    bank_timings: [
      {
        bank_id: "agent-06",
        elapsed_ms: 6414,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 532,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 2,
    total_elapsed_ms: 4799,
    pre_cap_count: 2,
    overlap_dropped: 51,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 4797,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1313,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 6,
    total_elapsed_ms: 5925,
    pre_cap_count: 8,
    overlap_dropped: 55,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 5923,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1266,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 1,
    total_elapsed_ms: 6579,
    pre_cap_count: 1,
    overlap_dropped: 45,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 6575,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1685,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 1,
    total_elapsed_ms: 5524,
    pre_cap_count: 1,
    overlap_dropped: 35,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 5521,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 3389,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 1,
    total_elapsed_ms: 4529,
    pre_cap_count: 1,
    overlap_dropped: 38,
    injected_score_max: 0.1927,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 4528,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1411,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 4,
    total_elapsed_ms: 4723,
    pre_cap_count: 4,
    overlap_dropped: 47,
    injected_score_max: 0.0499,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 4721,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 2018,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 5,
    total_elapsed_ms: 4383,
    pre_cap_count: 5,
    overlap_dropped: 50,
    injected_score_max: 0.9756,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 4382,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1225,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 1,
    total_elapsed_ms: 839,
    pre_cap_count: 1,
    overlap_dropped: 36,
    injected_score_max: 0.9571,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 838,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 343,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 1,
    total_elapsed_ms: 2739,
    pre_cap_count: 1,
    overlap_dropped: 40,
    injected_score_max: 0.0674,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 2738,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 1278,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 5,
    total_elapsed_ms: 3626,
    pre_cap_count: 5,
    overlap_dropped: 35,
    injected_score_max: 0.0001,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 3622,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 274,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 0,
    total_elapsed_ms: 1551,
    pre_cap_count: 0,
    overlap_dropped: 41,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 1550,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 580,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 6,
    total_elapsed_ms: 11859,
    pre_cap_count: 7,
    overlap_dropped: 30,
    injected_score_max: 0.0005,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 11851,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 413,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 6,
    total_elapsed_ms: 11426,
    pre_cap_count: 27,
    overlap_dropped: 15,
    injected_score_max: 0.8976,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 11420,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 637,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-07",
    bank_id: "agent-07",
    result_count: 6,
    total_elapsed_ms: 11353,
    pre_cap_count: 12,
    overlap_dropped: 26,
    injected_score_max: 0.0019,
    bank_timings: [
      {
        bank_id: "agent-07",
        elapsed_ms: 11342,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-01",
        elapsed_ms: 508,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-08",
    bank_id: "agent-08",
    result_count: 2,
    total_elapsed_ms: 7164,
    pre_cap_count: 2,
    overlap_dropped: 6,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-08",
        elapsed_ms: 7163,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-08",
    bank_id: "agent-08",
    result_count: 3,
    total_elapsed_ms: 7241,
    pre_cap_count: 3,
    overlap_dropped: 5,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-08",
        elapsed_ms: 7235,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-08",
    bank_id: "agent-08",
    result_count: 6,
    total_elapsed_ms: 7836,
    pre_cap_count: 8,
    overlap_dropped: 0,
    injected_score_max: 0.5794,
    bank_timings: [
      {
        bank_id: "agent-08",
        elapsed_ms: 7835,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-08",
    bank_id: "agent-08",
    result_count: 6,
    total_elapsed_ms: 8783,
    pre_cap_count: 9,
    overlap_dropped: 0,
    injected_score_max: 0.6419,
    bank_timings: [
      {
        bank_id: "agent-08",
        elapsed_ms: 8780,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-08",
    bank_id: "agent-08",
    result_count: 6,
    total_elapsed_ms: 6984,
    pre_cap_count: 8,
    overlap_dropped: 1,
    injected_score_max: 0.5861,
    bank_timings: [
      {
        bank_id: "agent-08",
        elapsed_ms: 6982,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-08",
    bank_id: "agent-08",
    result_count: 6,
    total_elapsed_ms: 7614,
    pre_cap_count: 8,
    overlap_dropped: 0,
    injected_score_max: 0.753,
    bank_timings: [
      {
        bank_id: "agent-08",
        elapsed_ms: 7608,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 0,
    total_elapsed_ms: 7816,
    pre_cap_count: 0,
    overlap_dropped: 61,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 7811,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 7084,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 0,
    total_elapsed_ms: 6379,
    pre_cap_count: 0,
    overlap_dropped: 59,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 6372,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 6368,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 1,
    total_elapsed_ms: 6618,
    pre_cap_count: 1,
    overlap_dropped: 44,
    injected_score_max: null,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 6613,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5889,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 5688,
    pre_cap_count: 8,
    overlap_dropped: 47,
    injected_score_max: 0.0002,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 5684,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5089,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 5902,
    pre_cap_count: 28,
    overlap_dropped: 32,
    injected_score_max: 0.4534,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 5896,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5307,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 5992,
    pre_cap_count: 29,
    overlap_dropped: 31,
    injected_score_max: 0.0601,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 5986,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5531,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 5956,
    pre_cap_count: 28,
    overlap_dropped: 33,
    injected_score_max: 0.4401,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 5950,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 5420,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 5421,
    pre_cap_count: 39,
    overlap_dropped: 25,
    injected_score_max: 0.4538,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 5415,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 4979,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 4683,
    pre_cap_count: 19,
    overlap_dropped: 7,
    injected_score_max: 0.0004,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 4680,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 4838,
    pre_cap_count: 45,
    overlap_dropped: 17,
    injected_score_max: 0.0413,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 4833,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 4462,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 491,
    pre_cap_count: 42,
    overlap_dropped: 25,
    injected_score_max: 0.8778,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 484,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 360,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 543,
    pre_cap_count: 31,
    overlap_dropped: 28,
    injected_score_max: 0.0619,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 538,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 431,
        timed_out: false,
        errored: false,
      },
    ],
  },
  {
    agent: "agent-09",
    bank_id: "agent-09",
    result_count: 6,
    total_elapsed_ms: 606,
    pre_cap_count: 31,
    overlap_dropped: 24,
    injected_score_max: 0.0021,
    bank_timings: [
      {
        bank_id: "agent-09",
        elapsed_ms: 601,
        timed_out: false,
        errored: false,
      },
      {
        bank_id: "side-02",
        elapsed_ms: 479,
        timed_out: false,
        errored: false,
      },
    ],
  },
];
