/**
 * model-unavailable.ts — graceful UX for the "model is down" failure modes.
 *
 * Issue #394 (Fix 2). When a user message hits Claude and the model is
 * unreachable — quota exhausted, overloaded / 429-storm, billing dead, or
 * the network simply timed out — the bridge used to relay Anthropic's raw
 * stderr verbatim ("You're out of extra usage · resets May 3, 11am"). The
 * desired UX is a clean ⚠️ card naming what failed and pointing at the
 * three actions that actually move the needle:
 *
 *   - /authfallback — auto-switch to next slot
 *   - /auth add     — attach another subscription
 *   - /usage        — full quota breakdown
 *
 * This module owns:
 *   1. `detectModelUnavailable(stderr)` — pattern-matches a raw error
 *      string into one of three structured kinds (overload / quota_exhausted
 *      / network), pulling out a reset Date when the source mentions one.
 *      Returns null on lines that don't look like a model-down event so
 *      callers can fall through to their default rendering.
 *   2. `formatModelUnavailableCard(detection, agent)` — renders the HTML
 *      card. Reset-time formatting routes through quota-check.ts's
 *      `formatResetRelative` so "/usage" and this card speak the same
 *      countdown dialect.
 *
 * Pure module: no IPC, no bot, no FS. Trivially unit-testable.
 */

import { formatResetRelative } from './quota-check.js'
import { escapeMarkdown } from './card-format.js'

// ─── Public types ────────────────────────────────────────────────────────────

export type ModelUnavailableKind =
  | 'overload'
  | 'quota_exhausted'
  | 'network'
  /**
   * 429 throttle tier — a TRANSIENT per-account 429 (explicit
   * `transientUpstreamSignals` negation wording) whose parsed reset lies
   * BEYOND the retry-in-place threshold, so the gateway escalates it to the
   * standard mark-exhausted + fleet-failover machinery. Never produced by
   * `detectModelUnavailable` (a transient-negation string classifies as
   * `overload` there); constructed only by the gateway's throttle-tier
   * branch so the card names the true cause instead of "quota exhausted".
   */
  | 'rate_limited'

export interface ModelUnavailableDetection {
  kind: ModelUnavailableKind
  /** When the source mentions a reset window, parsed best-effort to a Date. */
  resetAt?: Date
  /** The raw stderr string that triggered the detection. */
  raw: string
}

// ─── Transient-burst signals (canonical, single source of truth) ─────────────

/**
 * Explicit markers of a TRANSIENT per-account burst / server-side throttle —
 * a short-term RPM/burst 429 that Claude Code retries internally with backoff,
 * NOT the 5h/7d subscription usage-limit wall. Anthropic emits these with a
 * `rate_limit_error` whose wording explicitly NEGATES the account-quota reading
 * ("not your usage limit" / "would exceed your account's rate limit … try again
 * later"). Keyed on the explicit negation so a genuine wall that merely contains
 * the word "limit" is never down-classified.
 *
 * Exported so `session-tail.ts` classifies a 429 by wording against THIS list
 * rather than hand-rolling its own copy (keeps the two in sync — issue #2922).
 */
export const transientUpstreamSignals = [
  'not your usage limit',
  'not your account',
  "not your account's",
  'temporarily limiting requests',
  'temporarily rate',
  'server is temporarily',
  'would exceed your account’s rate limit',
  "would exceed your account's rate limit",
]

/**
 * True when `text` carries an EXPLICIT transient-burst marker (see
 * `transientUpstreamSignals`). Never throws on weird input. Used to keep the
 * calm rate-limit path and the model-unavailable detector reading the same
 * canonical signal list.
 */
export function isTransientUpstreamSignal(text: string): boolean {
  if (typeof text !== 'string' || text.length === 0) return false
  const sample = text.length > 16_384 ? text.slice(0, 16_384) : text
  const lower = sample.toLowerCase()
  return transientUpstreamSignals.some(s => lower.includes(s))
}

// ─── LiteLLM-proxy-LOCAL 429 signals (canonical, single source of truth) ─────

/**
 * Explicit markers of a 429 generated by the LiteLLM proxy's OWN rate
 * limiters — a router `tpm_limit`/`rpm_limit` deployment cap, a virtual-key /
 * team / user cap, or an all-deployments-cooling-down router state. The
 * request never reached Anthropic, so the condition is PROXY-LOCAL: it says
 * nothing about the Anthropic account's quota and must never mark the account
 * throttled/exhausted or trigger fleet failover.
 *
 * Each wording key is grounded in LiteLLM's source (verified against
 * BerriAI/litellm `main`, 2026-07), matching how
 * `accountScopedThrottleSignals` (throttle-tier.ts) documents its keys:
 *
 *  - "deployment over user-defined ratelimit" —
 *    `RouterErrors.user_defined_ratelimit_error` (litellm/types/router.py),
 *    the body prefix of every deployment tpm/rpm cap 429 raised by
 *    litellm/router_utils/pre_call_checks/model_rate_limit_check.py:
 *    "Deployment over user-defined ratelimit. tpm limit={n}. current
 *    usage={n}. id={id}, model_group={g}".
 *  - "model rate limit exceeded. tpm/rpm limit" — the `message` field of the
 *    same enforcement RateLimitError: "Model rate limit exceeded. TPM
 *    limit={n}, current usage={n}" (model_rate_limit_check.py).
 *  - "deployment over defined rpm limit" — the usage-based-routing-v2
 *    strategy wording "Deployment over defined rpm limit={n}. current
 *    usage={n}" (litellm/router_strategy/lowest_tpm_rpm_v2.py). There is NO
 *    tpm sibling in any known release — v2 TPM exhaustion surfaces as the
 *    `no_deployments_available` wording below (the deployment is filtered
 *    from the candidate set rather than erroring in the increment path).
 *  - "no deployments available for selected model" —
 *    `RouterErrors.no_deployments_available`, the RouterRateLimitError
 *    message when every deployment for the model group is cooling down:
 *    "No deployments available for selected model, Try again in {n}
 *    seconds…" (litellm/types/router.py).
 *  - "litellm rate limit handler" — the v1 parallel-request limiter's
 *    ProxyRateLimitError detail prefix: "LiteLLM Rate Limit Handler for
 *    rate limit type = {t}. Crossed TPM / RPM / Max Parallel Request
 *    Limit. current rpm: {n}, rpm limit: {n}…"
 *    (litellm/proxy/hooks/parallel_request_limiter.py).
 *  - "crossed tpm / rpm" — `CommonProxyErrors
 *    .max_parallel_request_limit_reached.value` = "Crossed TPM / RPM / Max
 *    Parallel Request Limit" (litellm/proxy/_types.py), interpolated into
 *    BOTH v1 detail shapes, so it also covers the zero-limit branch's
 *    "Max parallel request limit reached {additional_details}" message.
 *  - "max parallel request limit reached" — the standalone prefix
 *    `raise_rate_limit_error` builds when a key's limit is set to 0
 *    (parallel_request_limiter.py `error_message`).
 *
 * The proxy-side per-key/team/user limiter (parallel_request_limiter_v3.py
 * `_handle_rate_limit_error`) is matched by CO-OCCURRENCE instead of a
 * per-descriptor entry — see `isLitellmProxyLocal429`. Its detail shape:
 * "Rate limit exceeded for {descriptor}: {value}. Limit type: {t}. Current
 * limit: {n}, Remaining: {n}. Limit resets at: {ts}". Descriptor keys in
 * source are numerous and growing (api_key / user / team / team_member /
 * organization / end_user / agent / agent_session / model_per_key /
 * model_per_team / model_per_organization / model_per_project / tag_per_key
 * / mcp_per_key / mcp_per_team as of 2026-07), so enumerating them is a
 * treadmill: the pair "rate limit exceeded for " + "limit type:" appears in
 * every v3 body and in no Anthropic error. This is the shape a `tpm_limit`
 * on the per-agent virtual keys (src/litellm/provision.ts) trips.
 *
 * Deliberately EXCLUDED: the bare exception-mapping prefix
 * "litellm.RateLimitError:". LiteLLM wraps FORWARDED upstream 429s with the
 * same prefix on the pass-through, so its presence is NOT evidence the limit
 * was proxy-local — a genuine Anthropic account throttle traversing the
 * proxy must keep its account-scoped classification (see
 * `classify429Detail` in throttle-tier.ts for the tie-break).
 */
export const litellmProxyLocal429Signals = [
  'deployment over user-defined ratelimit',
  'model rate limit exceeded. tpm limit',
  'model rate limit exceeded. rpm limit',
  'deployment over defined rpm limit',
  'no deployments available for selected model',
  'litellm rate limit handler',
  'crossed tpm / rpm',
  'max parallel request limit reached',
]

/**
 * The v3 proxy-limiter co-occurrence pair (see the provenance comment on
 * `litellmProxyLocal429Signals`): both substrings appear in every
 * parallel_request_limiter_v3 429 body regardless of descriptor key, and
 * never in an Anthropic error. Exported so tests can pin the rule.
 */
export const litellmV3LimiterSignalPair = ['rate limit exceeded for ', 'limit type:'] as const

/**
 * True when `text` carries an EXPLICIT LiteLLM-proxy-local rate-limit marker:
 * one of `litellmProxyLocal429Signals`, OR the v3 limiter co-occurrence pair
 * (`litellmV3LimiterSignalPair` — descriptor-agnostic, so new v3 descriptor
 * keys are covered without a list update). Never throws on weird input. Pure
 * wording detection only — precedence against account-scoped wording is
 * owned by `classify429Detail` (throttle-tier.ts).
 */
export function isLitellmProxyLocal429(text: string): boolean {
  if (typeof text !== 'string' || text.length === 0) return false
  const sample = text.length > 16_384 ? text.slice(0, 16_384) : text
  const lower = sample.toLowerCase()
  if (litellmProxyLocal429Signals.some(s => lower.includes(s))) return true
  return litellmV3LimiterSignalPair.every(s => lower.includes(s))
}

/**
 * True when `text` is a LiteLLM-proxy-LOCAL AUTH misconfiguration — the
 * proxy-fallback keyless-401 class, NOT a genuine end-user credential wall.
 *
 * PROVENANCE (incident, 2026-07-16). LiteLLM's internal model-fallback chain
 * (`gpt-oss-20b -> [gpt-oss-20b-openrouter, claude-sonnet-5]`) re-dispatches a
 * failed primary WITHOUT forwarding the client's OAuth `Authorization` header.
 * The `claude-sonnet-5` deployment is deliberately keyless (passthrough auth —
 * it expects the forwarded OAuth), so Anthropic rejects the header-less
 * fallback with a 401 `authentication_error` whose message is
 * "x-api-key header is required". Switchroom agents authenticate the unmodified
 * `claude` CLI with an OAuth Bearer token and NEVER an `x-api-key`, so that
 * demand can only originate from the proxy dropping the header on a keyless
 * fallback deployment — a host-side infra misconfig for the OPERATOR to fix,
 * never a login problem an end user (or even the operator's OAuth) can act on.
 *
 * Misclassifying it (as `classifyClaudeError` did → `credentials-invalid` →
 * a "🔑 re-authenticate" card) is doubly wrong: wrong AUDIENCE (a non-operator
 * user like Lisa cannot re-auth anything) and wrong DIAGNOSIS (the login is
 * fine; the proxy fallback config is not). Detecting it here lets both
 * classifiers route it to the operator-only infra surface instead.
 *
 * Detection (deterministic wording, mirrors `isLitellmProxyLocal429`):
 *   - the definitive "x-api-key header is required" marker (impossible for our
 *     OAuth flow — only the keyless-proxy path emits it), OR
 *   - an `authentication_error` CO-OCCURRING with the proxy-FALLBACK-specific
 *     structural pair: "fallback" re-dispatch provenance AND an explicit
 *     "x-api-key" mention.
 *
 * PRECISION over recall (#3293 review finding 2): an earlier draft matched any
 * `authentication_error` + (litellm|proxy) + (fallback|x-api-key|api_key) —
 * broad enough that a GENUINE OAuth expiry wrapped in a proxy envelope that
 * merely mentions "api_key" would misdiagnose as proxy-misconfig (still
 * operator-visible, but the recommendation would point at the proxy config
 * instead of a re-auth). Both classes route operator-only now, so an ambiguous
 * envelope deliberately KEEPS the credentials-invalid/-expired diagnosis;
 * only the unambiguous keyless-fallback signature classifies as misconfig.
 * Never throws on weird input.
 */
export function isLitellmProxyAuthMisconfig(text: string): boolean {
  if (typeof text !== 'string' || text.length === 0) return false
  const sample = text.length > 16_384 ? text.slice(0, 16_384) : text
  const lower = sample.toLowerCase()
  // Definitive marker — see provenance above.
  if (lower.includes('x-api-key header is required')) return true
  // Structural signature: an authentication_error carrying BOTH the fallback
  // re-dispatch provenance AND an explicit x-api-key mention. A proxy envelope
  // that merely mentions litellm/proxy/api_key stays on the credentials
  // diagnosis (ambiguous → not misconfig).
  const isAuthErr =
    lower.includes('authentication_error') || lower.includes('authenticationerror')
  if (!isAuthErr) return false
  return lower.includes('fallback') && lower.includes('x-api-key')
}

/**
 * Best-effort extraction of the limit detail LiteLLM embeds in its
 * proxy-local 429 bodies, for instrumentation (the `rate_limit_429_classified`
 * runtime metric). All fields null when nothing parseable is found — never
 * throws. Shapes covered (same provenance as `litellmProxyLocal429Signals`):
 *
 *   - "tpm limit=8000. current usage=8241"    (model_rate_limit_check body)
 *   - "TPM limit=8000, current usage=8241"    (model_rate_limit_check message)
 *   - "Deployment over defined rpm limit=60. current usage=61"  (v2 strategy)
 *   - "Limit type: tokens. Current limit: 8000 … Limit resets at:
 *      2026-07-12 08:05:00 UTC"               (parallel_request_limiter_v3)
 *   - "Try again in 27.5 seconds"             (RouterRateLimitError cooldown)
 *
 * CAVEAT — the v3 "Limit resets at" timestamp is NOT reliably UTC despite
 * the literal: litellm formats it with a naive `datetime.fromtimestamp(...)
 * .strftime("%Y-%m-%d %H:%M:%S UTC")` (parallel_request_limiter_v3.py
 * `_handle_rate_limit_error`), i.e. proxy-LOCAL wall-clock time with a
 * hard-coded "UTC" suffix. We parse it as UTC (nothing better is possible
 * from the body alone), so `resetAtMs` — and the metric fields derived from
 * it — can be skewed by the proxy host's UTC offset when the proxy doesn't
 * run on UTC. Treat v3-derived resets as approximate; don't chase phantom
 * clock drift from these metrics. The rate-limit windows are ≤1 minute
 * anyway, so the absolute timestamp is informational.
 */
export function parseLitellmLimitDetail(
  text: string,
  parseTimeNow: Date = new Date(),
): {
  limitType: string | null
  limit: number | null
  currentUsage: number | null
  resetAtMs: number | null
} {
  const empty = { limitType: null, limit: null, currentUsage: null, resetAtMs: null }
  if (typeof text !== 'string' || text.length === 0) return empty
  const sample = text.length > 16_384 ? text.slice(0, 16_384) : text
  const lower = sample.toLowerCase()

  // "tpm limit=8000" / "rpm limit=60" (body), "TPM limit=8000" (message),
  // and the v1 limiter's colon form "rpm limit: 60".
  let limitType: string | null = null
  let limit: number | null = null
  const eqLimit = lower.match(/\b([tr]pm)[ _]limit[=:]\s*(\d+)/)
  if (eqLimit) {
    limitType = eqLimit[1]
    limit = Number(eqLimit[2])
  }
  // v3 limiter: "Limit type: tokens. Current limit: 8000"
  if (limitType == null) {
    const v3Type = lower.match(/limit type:\s*(tokens|requests|max_parallel_requests)/)
    if (v3Type) limitType = v3Type[1]
  }
  if (limit == null) {
    const v3Limit = lower.match(/current limit:\s*(\d+)/)
    if (v3Limit) limit = Number(v3Limit[1])
  }

  // "current usage=8241" (body/message, both `=` and `= ` never occur with
  // separators other than the literal shown in source).
  let currentUsage: number | null = null
  const usage = lower.match(/current usage=(\d+)/)
  if (usage) currentUsage = Number(usage[1])

  // Reset hints LiteLLM emits that the Anthropic-shaped parseResetTime does
  // not cover: "Limit resets at: 2026-07-12 08:05:00 UTC" (v3 limiter — note
  // the space separator, not ISO 'T') and "Try again in 27.5 seconds"
  // (RouterRateLimitError).
  let resetAtMs: number | null = null
  const resetsAt = sample.match(
    /limit resets at:\s*(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}:\d{2}) UTC/i,
  )
  if (resetsAt) {
    const d = new Date(`${resetsAt[1]}T${resetsAt[2]}Z`)
    if (!Number.isNaN(d.getTime())) resetAtMs = d.getTime()
  }
  if (resetAtMs == null) {
    const tryAgain = lower.match(/try again in\s+(\d+(?:\.\d+)?)\s*seconds/)
    if (tryAgain) {
      const secs = Number(tryAgain[1])
      if (Number.isFinite(secs) && secs > 0 && secs < 7 * 24 * 3600) {
        resetAtMs = parseTimeNow.getTime() + Math.round(secs * 1000)
      }
    }
  }

  return {
    limitType,
    limit: limit != null && Number.isFinite(limit) ? limit : null,
    currentUsage:
      currentUsage != null && Number.isFinite(currentUsage) ? currentUsage : null,
    resetAtMs,
  }
}

// ─── Detection ───────────────────────────────────────────────────────────────

/**
 * Inspect a raw stderr / error-message string for one of the known
 * model-unavailable patterns. Returns null when the line doesn't look
 * like one — never throws on weird input.
 *
 * Detection rules (matched in priority order):
 *   1. Quota / billing-style strings ("out of extra usage", "credit_balance_too_low",
 *      "usage limit", "quota exhausted") → quota_exhausted
 *   2. Overload / 429 / 5xx signals ("overloaded_error", "rate_limit_error",
 *      "HTTP 429", "Service Unavailable", "503", "529") → overload
 *   3. Network-layer failures (DNS, ECONNREFUSED, ETIMEDOUT, "fetch failed",
 *      "network error", "socket hang up") → network
 *
 * Quota strings can also carry a reset-time hint ("resets May 3, 11am",
 * "resets in 2h 15m", "retry after 60 seconds", ISO 8601). When present
 * and parseable, the Date is attached.
 */
export function detectModelUnavailable(
  stderr: string,
): ModelUnavailableDetection | null {
  if (typeof stderr !== 'string' || stderr.length === 0) return null
  // Defend against pathological input — anything beyond a few KB is almost
  // certainly not a clean error string and risks a regex stall.
  const sample = stderr.length > 16_384 ? stderr.slice(0, 16_384) : stderr
  const lower = sample.toLowerCase()

  // ── 0. Transient / server-side 429 (NOT account quota) — issue #2922 ────
  // Anthropic emits a `rate_limit_error` whose message explicitly negates the
  // account-quota reading: "Server is temporarily limiting requests (not your
  // usage limit)". A negation-blind substring match on "usage limit" (step 1
  // below) would misclassify this as `quota_exhausted`, firing a phantom fleet
  // failover that self-cancels and leaves the turn dead. These are upstream
  // throttles Claude Code retries internally with backoff — classify them as
  // `overload` (the calm rate-limit path) BEFORE the quota substrings run, so
  // the negation is honoured and no failover is announced. The signal list is
  // module-level (`transientUpstreamSignals`) so session-tail.ts classifies a
  // 429 against the SAME canonical wording.
  if (transientUpstreamSignals.some(s => lower.includes(s))) {
    const resetAt = parseResetTime(sample)
    return resetAt !== undefined
      ? { kind: 'overload', resetAt, raw: stderr }
      : { kind: 'overload', raw: stderr }
  }

  // ── 0.5. LiteLLM-proxy-LOCAL 429 — never a quota signal ─────────────────
  // A 429 raised by the LiteLLM proxy's own limiters (`tpm_limit`/`rpm_limit`
  // caps, router cooldown) never reached Anthropic — nothing about the
  // account is exhausted, so it must classify to the calm retryable kind
  // BEFORE the quota substrings run (some LiteLLM bodies contain the word
  // "limit", which a negation-blind quota match could seize on). Runs after
  // step 0 deliberately: account-affirming wording, when present, can only
  // have originated upstream (LiteLLM never emits it) and wins — see the
  // tie-break note on `classify429Detail` (throttle-tier.ts). Uses the full
  // matcher (list + v3 co-occurrence pair) so every descriptor is covered.
  if (isLitellmProxyLocal429(sample)) {
    const resetAt = parseResetTime(sample)
    return resetAt !== undefined
      ? { kind: 'overload', resetAt, raw: stderr }
      : { kind: 'overload', raw: stderr }
  }

  // ── 1. Quota / billing exhaustion ──────────────────────────────────────
  const quotaSignals = [
    'out of extra usage',
    'extra usage',
    'credit_balance_too_low',
    'credit balance too low',
    'usage limit',
    'usage_limit',
    'quota exhausted',
    'quota_exhausted',
    'plan limit',
    'subscription limit',
    // Claude Code v2.1.x usage-limit wording: "You've hit your limit ·
    // resets 8:50am (Australia/Melbourne)".
    'hit your limit',
    'hit the limit',
    // SESSION-cap wording: "You've hit your session limit · resets 5pm".
    // A session cap is a quota exhaustion that frees in HOURS (its reset is a
    // bare time-of-day, see parseResetTime's time-only branch) — recognising
    // it here is what lets the time-only reset parse fire and keeps a
    // session-capped account from the +7d weekly bench.
    'session limit',
    'session cap',
  ]
  if (quotaSignals.some(s => lower.includes(s))) {
    const resetAt = parseResetTime(sample)
    return resetAt !== undefined
      ? { kind: 'quota_exhausted', resetAt, raw: stderr }
      : { kind: 'quota_exhausted', raw: stderr }
  }

  // ── 2. Overload / 429 / 5xx ────────────────────────────────────────────
  const overloadSignals = [
    'overloaded_error',
    'overloaded',
    'rate_limit_error',
    'rate limit',
    'rate-limited',
    'http 429',
    '"status":429',
    'status: 429',
    ' 429 ',
    '503 service',
    'service unavailable',
    '"status":529',
    'http 529',
    ' 529 ',
  ]
  if (overloadSignals.some(s => lower.includes(s))) {
    const resetAt = parseResetTime(sample)
    return resetAt !== undefined
      ? { kind: 'overload', resetAt, raw: stderr }
      : { kind: 'overload', raw: stderr }
  }

  // ── 3. Network-layer failure ───────────────────────────────────────────
  const networkSignals = [
    'econnrefused',
    'econnreset',
    'etimedout',
    'enotfound',
    'eai_again',
    'fetch failed',
    'network error',
    'socket hang up',
    'request timed out',
    'connection refused',
    'getaddrinfo',
  ]
  if (networkSignals.some(s => lower.includes(s))) {
    return { kind: 'network', raw: stderr }
  }

  return null
}

/**
 * Best-effort reset-time extraction. Tries, in order:
 *   - "retry after N seconds" / "retry-after: N"
 *   - "resets in 2h 15m" (relative — anchored at parseTimeNow)
 *   - "resets May 3, 11am" / "resets at May 3 11:00"
 *   - bare ISO-8601 timestamp anywhere in the string
 *
 * Returns undefined when nothing parseable is found. The `parseTimeNow`
 * arg lets tests pin the relative-clock anchor; production callers omit
 * it to use Date.now().
 */
export function parseResetTime(text: string, parseTimeNow: Date = new Date()): Date | undefined {
  const lower = text.toLowerCase()

  // "retry after 60 seconds" / "retry-after: 60"
  const retryAfter = lower.match(/retry[\s-]*after[:\s]+(\d+)\s*(seconds?|s\b|minutes?|m\b|hours?|h\b)?/)
  if (retryAfter) {
    const n = Number(retryAfter[1])
    if (Number.isFinite(n) && n > 0 && n < 7 * 24 * 3600) {
      const unit = (retryAfter[2] ?? 'seconds').toLowerCase()
      const ms = unit.startsWith('h')
        ? n * 3600_000
        : unit.startsWith('m')
        ? n * 60_000
        : n * 1000
      return new Date(parseTimeNow.getTime() + ms)
    }
  }

  // "resets in 2h 15m" / "resets in 30 minutes"
  const relReset = lower.match(/resets?\s+in\s+([0-9hms\s]+)/)
  if (relReset) {
    const ms = parseRelativeDuration(relReset[1])
    if (ms != null) return new Date(parseTimeNow.getTime() + ms)
  }

  // ISO-8601 timestamp anywhere in the text
  const iso = text.match(/\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?\b/)
  if (iso) {
    const d = new Date(iso[0])
    if (!Number.isNaN(d.getTime())) return d
  }

  // "resets May 3, 11am" / "resets May 3 at 11:00"
  // Conservative regex — avoid greedy backtracking on long strings.
  const calReset = text.match(
    /resets?\s+(?:at\s+)?([A-Z][a-z]{2,8}\s+\d{1,2}(?:,?\s*(?:\d{1,2}(?::\d{2})?\s*(?:am|pm|AM|PM)?))?)/,
  )
  if (calReset) {
    // Anchor to the current year — Anthropic's user-facing strings omit it.
    const candidate = `${calReset[1]} ${parseTimeNow.getUTCFullYear()}`
    const d = new Date(candidate)
    if (!Number.isNaN(d.getTime())) return d
  }

  // "resets 5pm (Australia/Melbourne)" / "resets 8:50am" / "resets 17:00 (UTC)"
  // SESSION-cap wording: a time of day with NO month/day. This frees in
  // HOURS, not a week — without this branch it falls through to undefined,
  // and the 429 inference path then applies resolveExhaustUntil's +7d weekly
  // floor, benching a session-capped account for a week. Must sit AFTER the
  // calendar branch so "resets May 3, 11am" never matches here. The leading
  // negative lookahead `(?!...)` rejects a month name so a date-bearing
  // string can't fall into this time-only branch.
  const timeOnly = text.match(
    /resets?\s+(?:at\s+)?(?!(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b)(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*(?:\(([^)]+)\))?/i,
  )
  if (timeOnly) {
    const d = resolveNextWallClock(
      Number(timeOnly[1]),
      timeOnly[2] ? Number(timeOnly[2]) : 0,
      timeOnly[3]?.toLowerCase(),
      timeOnly[4]?.trim(),
      parseTimeNow,
    )
    if (d != null) return d
  }

  return undefined
}

/**
 * Resolve a bare wall-clock time ("5pm", "8:50am", "17:00") to the NEXT
 * occurrence of that time, tz-aware. Returns the soonest future Date (rolls
 * to tomorrow when the time has already passed today). Null on bad input
 * (out-of-range hour/minute or an unknown tz). When `tz` is omitted the
 * time is interpreted in UTC (best-effort) — Anthropic's strings normally
 * carry the IANA tz in parens, e.g. "(Australia/Melbourne)".
 */
function resolveNextWallClock(
  hour12or24: number,
  minute: number,
  ampm: string | undefined,
  tz: string | undefined,
  nowDate: Date,
): Date | undefined {
  let hour = hour12or24
  if (ampm === 'pm' && hour < 12) hour += 12
  if (ampm === 'am' && hour === 12) hour = 0
  if (!Number.isFinite(hour) || hour > 23 || hour < 0) return undefined
  if (!Number.isFinite(minute) || minute > 59 || minute < 0) return undefined
  const nowMs = nowDate.getTime()
  // Walk today and the next two days (DST-safe span) and pick the first
  // occurrence strictly in the future relative to now.
  const base = new Date(nowMs)
  for (let dayOffset = 0; dayOffset <= 2; dayOffset++) {
    // Derive the y/m/d for `dayOffset` days from now IN THE TARGET TZ, so the
    // wall-clock date we resolve is the tz's calendar date, not the container's.
    const dateParts = tzDateParts(new Date(nowMs + dayOffset * 86_400_000), tz)
    if (dateParts == null) return undefined
    const epoch = wallClockToEpoch(
      dateParts.year, dateParts.month, dateParts.day, hour, minute, tz,
    )
    if (epoch != null && epoch > nowMs) return new Date(epoch)
  }
  // Fallback: shouldn't happen, but keep the function total.
  void base
  return undefined
}

/** The y/m/d of `d` as seen in `tz` (UTC when tz omitted). Null on bad tz. */
function tzDateParts(
  d: Date,
  tz: string | undefined,
): { year: number; month: number; day: number } | null {
  if (!tz) {
    return { year: d.getUTCFullYear(), month: d.getUTCMonth(), day: d.getUTCDate() }
  }
  try {
    const fmt = new Intl.DateTimeFormat('en-US', {
      timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit',
    })
    const parts = Object.fromEntries(
      fmt.formatToParts(d).filter((p) => p.type !== 'literal').map((p) => [p.type, p.value]),
    )
    return {
      year: Number(parts.year),
      month: Number(parts.month) - 1,
      day: Number(parts.day),
    }
  } catch {
    return null
  }
}

/**
 * Convert a wall-clock time in an IANA tz to epoch-ms (null if the tz is
 * unknown). Resolves the tz's offset AT that date via Intl, so it is correct
 * across DST — NOT `new Date(localString)`, which assumes the container TZ.
 * Mirrors wedge-watchdog.ts's helper of the same name (kept local to keep
 * this module dependency-free / pure-testable).
 */
function wallClockToEpoch(
  year: number, month: number, day: number, hour: number, minute: number, tz: string | undefined,
): number | null {
  const asUtc = Date.UTC(year, month, day, hour, minute, 0)
  if (!tz) return asUtc // no tz given → best-effort UTC
  try {
    const fmt = new Intl.DateTimeFormat('en-US', {
      timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
    })
    const parts = Object.fromEntries(
      fmt.formatToParts(new Date(asUtc)).filter((p) => p.type !== 'literal').map((p) => [p.type, p.value]),
    )
    const shown = Date.UTC(
      Number(parts.year), Number(parts.month) - 1, Number(parts.day),
      Number(parts.hour) % 24, Number(parts.minute), Number(parts.second),
    )
    const offset = shown - asUtc // how far ahead the tz wall clock is of UTC
    return asUtc - offset
  } catch {
    return null // unknown tz
  }
}

function parseRelativeDuration(s: string): number | null {
  // "2h 15m" / "30m" / "45 seconds"
  let total = 0
  let matched = false
  const re = /(\d+)\s*(h|hours?|m|minutes?|s|seconds?)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(s)) != null) {
    matched = true
    const n = Number(m[1])
    const unit = m[2].toLowerCase()
    if (unit.startsWith('h')) total += n * 3600_000
    else if (unit.startsWith('m')) total += n * 60_000
    else total += n * 1000
  }
  return matched && total > 0 ? total : null
}

// ─── Card rendering ──────────────────────────────────────────────────────────

export interface FormatCardOptions {
  /** Slot the agent was using when the failure happened — when known,
   *  named in the card so the user can act precisely. */
  slot?: string | null
  /** Anchor for relative-time formatting. Tests pin this; prod omits it. */
  now?: Date
  /**
   * True when the gateway has concurrently fired
   * `fireFleetAutoFallback` for this event. Switches the card body
   * from "What to try" (manual commands) to "Auto-failover in
   * progress" so the user doesn't manually `/auth use` while a
   * fleet swap is mid-flight. Caller MUST pass this when invoking
   * the dispatcher in parallel — otherwise the card lies.
   */
  autoFallbackInFlight?: boolean
}

/**
 * Render the actionable ⚠️ card for a detected model-unavailable event.
 * HTML-formatted for Telegram. Stable shape so snapshot tests remain
 * meaningful when the suggestion list shifts.
 */
export function formatModelUnavailableCard(
  detection: ModelUnavailableDetection,
  agent: string,
  opts: FormatCardOptions = {},
): string {
  const now = opts.now ?? new Date()
  const slotPart = opts.slot ? ` (slot **${escapeMarkdown(opts.slot)}**)` : ''
  const reason = formatReason(detection, now)
  const lines = [
    `⚠️ **Model unavailable** on agent **${escapeMarkdown(agent)}**${slotPart}`,
    `Reason: ${reason}`,
    '',
  ]
  if (opts.autoFallbackInFlight) {
    // Quiet variant — the gateway already kicked off a fleet-wide
    // swap; a follow-up announcement (causal-shape) will land within
    // ~1s. Mention it explicitly so the user knows not to react.
    lines.push(
      '_Auto-failover in progress — see the announcement below._',
    )
  } else {
    // Default — kinds where auto-fallback can't help (network)
    // or pre-Format-2 callers. Also: `/authfallback` is no longer
    // a verb (post-RFC-H); `/auth use <label>` is the canonical
    // fleet-wide swap.
    lines.push(
      '**What to try**',
      '• \`/auth use <label>\` — switch the fleet to a healthy account',
      '• \`/auth add\` — attach another subscription',
      '• \`/usage\` — show quota breakdown',
    )
  }
  return lines.join('\n')
}

function formatReason(d: ModelUnavailableDetection, now: Date): string {
  const reset = d.resetAt ? ` (${formatResetRelative(d.resetAt, now)})` : ''
  switch (d.kind) {
    case 'quota_exhausted':
      return `quota exhausted${reset}`
    case 'overload':
      return `model overloaded${reset}`
    case 'rate_limited':
      // Throttle-tier escalation (429 with transient wording but a reset too
      // far out to wait in place). Honest cause: the account is rate-limited,
      // not quota-exhausted — the reset names when it frees.
      return `account rate-limited${reset}`
    case 'network':
      return 'network unreachable'
  }
}

// ─── Operator-event bridge ───────────────────────────────────────────────────

/**
 * Minimal shape for the operator-event input — kept structural to avoid a
 * runtime dependency on `operator-events.ts`. The gateway passes its real
 * `OperatorEvent` here; tests can pass a hand-rolled object with just the
 * `kind` and `detail` fields.
 *
 * The string union covers exactly the kinds that are model-availability-
 * relevant. Any kind outside that set falls through to text-pattern
 * detection on `detail`.
 */
export interface OperatorEventLike {
  kind: string
  detail: string
}

/**
 * Decide whether an operator event represents a model-unavailable failure.
 * Returns null when it's something else (auth issue, agent crash, etc.) so
 * the caller can fall back to its default per-kind renderer.
 *
 * Used by the gateway's `emitGatewayOperatorEvent` to decide whether to
 * suppress the raw stderr-style `detail` and post the actionable card
 * instead. Lives here (not in the gateway) so it's pure-testable without
 * spinning up the bot.
 *
 * Decision order:
 *   1. If the kind is one of the known model-unavailable kinds, build a
 *      synthetic detection from kind + detail (passing detail through
 *      `detectModelUnavailable` first to pick up reset-time hints).
 *   2. Otherwise, run pattern detection on `detail` — covers cases where
 *      a generic 4xx/5xx slipped past the upstream classifier carrying
 *      a quota/overload message in its body.
 */
export function resolveModelUnavailableFromOperatorEvent(
  ev: OperatorEventLike,
): ModelUnavailableDetection | null {
  const detail = typeof ev.detail === 'string' ? ev.detail : ''
  // A THIRD-PARTY provider credit wall is never "model unavailable" in the
  // Anthropic sense. Returning a detection here would route the event into the
  // `modelUnavailable` branch of emitGatewayOperatorEvent, which renders the
  // "⚠️ Model unavailable" card AND — for a `quota_exhausted` detection —
  // fires `fireFleetAutoFallback`, benching a perfectly healthy Anthropic
  // account slot because OpenRouter ran out of money. Return null so the event
  // takes the plain `renderOperatorEvent` path with its provider-specific card.
  if (ev.kind === 'provider-credit-exhausted') return null
  if (ev.kind === 'quota-exhausted') {
    return detectModelUnavailable(detail) ?? { kind: 'quota_exhausted', raw: detail }
  }
  if (ev.kind === 'rate-limited') {
    // A rate-limited / transient overload is NOT "model unavailable" —
    // it is retryable and Claude Code retries it internally. Escalate
    // to the model-unavailable card ONLY if the detail carries a
    // genuine quota signal (a 4xx that slipped past the classifier
    // with usage-limit wording in its body). A bare overload /
    // rate-limit returns null → the caller renders the calm
    // `rate-limited` card, never the scary "⚠️ Model unavailable" one.
    // Returning `{kind:'overload'}` here is what fired a false
    // model-unavailable card on every transient 529.
    const detected = detectModelUnavailable(detail)
    return detected?.kind === 'quota_exhausted' ? detected : null
  }
  if (ev.kind === 'unknown-5xx') {
    return detectModelUnavailable(detail) ?? { kind: 'overload', raw: detail }
  }
  return detectModelUnavailable(detail)
}

// ─── HTML escape (mirrors operator-events.ts) ────────────────────────────────
