#!/usr/bin/env node
// Build script for npm publish — bundles CLI + fixes shebang for Node.
// Runs under bun (preferred) or node (with esbuild fallback if bun missing).
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, chmodSync, mkdirSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { escapeBundleNonAscii } from "./escape-bundle-non-ascii.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "dist/cli");
const outFile = resolve(outDir, "switchroom.js");

// --- Build-time constants ---------------------------------------------------
// Emit src/build-info.ts so the runtime can import VERSION + git metadata.
// On a fresh checkout outside git (npm consumer tarball), gracefully fall
// back to null git fields and version-only data.
function tryGit(cmd) {
  try {
    return execSync(cmd, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function generateBuildInfo() {
  const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"));
  const version = pkg.version;

  const inGit = tryGit("git rev-parse --is-inside-work-tree") === "true";

  const commitSha = inGit ? tryGit("git rev-parse --short HEAD") : null;
  const commitDate = inGit ? tryGit("git log -1 --format=%cI") : null;
  const subject = inGit ? tryGit("git log -1 --pretty=%s") : null;
  const prMatch = subject ? subject.match(/\(#(\d+)\)\s*$/) : null;
  const latestPr = prMatch ? Number(prMatch[1]) : null;

  // Commits ahead of nearest tag. `null` if no tags exist or git missing.
  let commitsAhead = null;
  if (inGit) {
    const lastTag = tryGit("git describe --tags --abbrev=0");
    if (lastTag) {
      const ahead = tryGit(`git rev-list --count ${lastTag}..HEAD`);
      commitsAhead = ahead != null ? Number(ahead) : null;
    }
  }

  const out = `// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.
// Tracked in git so \`tsc --noEmit\` works on a fresh clone before \`npm run build\`.
// Values are refreshed every time \`npm run build\` runs.

export const VERSION: string = ${JSON.stringify(version)};
export const COMMIT_SHA: string | null = ${JSON.stringify(commitSha)};
export const COMMIT_DATE: string | null = ${JSON.stringify(commitDate)};
export const LATEST_PR: number | null = ${JSON.stringify(latestPr)};
export const COMMITS_AHEAD_OF_TAG: number | null = ${JSON.stringify(commitsAhead)};
`;
  writeFileSync(resolve(root, "src/build-info.ts"), out);
  console.log(
    `[build] generated src/build-info.ts (v${version}` +
      (commitSha ? ` · ${commitSha}` : "") +
      (commitsAhead != null ? ` · +${commitsAhead}` : "") +
      `)`
  );
}

generateBuildInfo();

console.log("[build] cleaning dist/");
rmSync(resolve(root, "dist"), { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

// Prefer bun (already a dev dep / runtime). Fall back to a clear error if missing.
let hasBun = false;
try {
  execSync("bun --version", { stdio: "ignore" });
  hasBun = true;
} catch {}

if (!hasBun) {
  console.error("[build] bun is required to build. Install from https://bun.sh");
  process.exit(1);
}

console.log("[build] bundling bin/switchroom.ts -> dist/cli/switchroom.js");
execSync(
  `bun build ${JSON.stringify(resolve(root, "bin/switchroom.ts"))} --outdir ${JSON.stringify(outDir)} --target node`,
  { stdio: "inherit", cwd: root }
);

// Rewrite shebang from `node` to `bun` — bun:sqlite and other bun: imports
// are not polyfillable in Node, and bun is already a hard runtime dependency
// (broker uses it explicitly, gateway runs `bun gateway.ts`, build itself
// requires `bun install`). Running the bundle under node produces an
// immediate ERR_UNSUPPORTED_ESM_URL_SCHEME 'bun:' error.
console.log("[build] rewriting shebang -> bun");
let src = readFileSync(outFile, "utf8");
if (src.startsWith("#!/usr/bin/env node")) {
  src = src.replace(/^#!\/usr\/bin\/env node/, "#!/usr/bin/env bun");
  writeFileSync(outFile, src);
}
chmodSync(outFile, 0o755);

// Bun parser bug workaround — see scripts/escape-bundle-non-ascii.mjs.
// Without this, raw UTF-8 in string literals past ~172kB into the bundle
// gets read as Latin-1 at runtime, producing double-UTF-8 mojibake in
// stdout (agent-list "Uptime" column) and on-disk files (systemd unit
// em-dash → `c3 a2 c2 80 c2 94`).
const cliEscape = escapeBundleNonAscii(outFile);
if (cliEscape.changed) {
  console.log(`[build] ASCII-escaped ${cliEscape.nonAsciiCount} non-ASCII code units in dist/cli/switchroom.js`);
}

// Bundle the autoaccept-poll entrypoint. The agent unit's ExecStartPost
// invokes this in the background to dispatch first-run TUI prompts via
// `tmux capture-pane` + `tmux send-keys`. Must ship in dist/ because
// package.json files-array does not include src/.
console.log("[build] bundling src/cli/autoaccept-poll.ts -> dist/cli/autoaccept-poll.js");
execSync(
  `bun build ${JSON.stringify(resolve(root, "src/cli/autoaccept-poll.ts"))} --outdir ${JSON.stringify(outDir)} --target node`,
  { stdio: "inherit", cwd: root }
);
const pollOutFile = resolve(outDir, "autoaccept-poll.js");
let pollSrc = readFileSync(pollOutFile, "utf8");
if (pollSrc.startsWith("#!/usr/bin/env node")) {
  pollSrc = pollSrc.replace(/^#!\/usr\/bin\/env node/, "#!/usr/bin/env bun");
  writeFileSync(pollOutFile, pollSrc);
}
chmodSync(pollOutFile, 0o755);
const pollEscape = escapeBundleNonAscii(pollOutFile);
if (pollEscape.changed) {
  console.log(`[build] ASCII-escaped ${pollEscape.nonAsciiCount} non-ASCII code units in dist/cli/autoaccept-poll.js`);
}

// Build the telegram-plugin self-contained dist (#634 strategic
// packaging fix). The plugin's gateway / server / bridge entry points
// reach across into `src/` (auth, config, vault-broker, build-info).
// Direct .ts execution from the npm package fails because the root
// package's `files` array doesn't ship `src/` and .gitignore excludes
// `dist/`. Bundling here resolves all cross-imports into a single
// dist/ tree per entry; combined with the explicit
// `telegram-plugin/dist` files-array entry below, the published
// tarball ships ready-to-run gateway/server/bridge JS.
const pluginScript = resolve(root, "telegram-plugin/scripts/build.mjs");
console.log("[build] bundling telegram-plugin/{server,gateway,bridge} -> telegram-plugin/dist/");
execSync(`node ${JSON.stringify(pluginScript)}`, { stdio: "inherit", cwd: root });

// Phase 1b: bundle the long-running server entry points that ship inside
// the docker images (broker / kernel / agent-scheduler). The Dockerfiles'
// CMDs reference /opt/switchroom/dist/{vault/broker/server.js,
// vault/approvals/kernel-server.js, agent-scheduler/index.js}; without
// these bundles the containers boot to MODULE_NOT_FOUND. Native deps
// (better-sqlite3, node-cron) are marked external — they're
// npm-installed inside the agent image so the prebuilt binary matches
// the linux/glibc runtime, not the host that ran `npm run build`.
const serverEntries = [
  { src: "src/vault/broker/server.ts", out: "dist/vault/broker/server.js" },
  // Phase 1c: kernel-server entrypoint. Closes the Phase 1b carry-forward
  // ("kernel image's CMD points at a file that doesn't exist"). Same
  // bundle discipline as the broker — bun:sqlite is bun-runtime-only so
  // the image runs the bundle under `bun`.
  { src: "src/vault/approvals/kernel-server.ts", out: "dist/vault/approvals/kernel-server.js" },
  // Cron-fold-in: in-agent scheduler sibling. Baked into the agent image
  // at /opt/switchroom/agent-scheduler/index.js and started by start.sh
  // as a sibling of the gateway. node-cron is npm-installed inside the
  // agent image (docker/Dockerfile.agent) so the prebuilt binary lines
  // up with the linux/glibc runtime, not whatever ran `npm run build`.
  // The host-side singleton scheduler bundle (`dist/scheduler/index.js`)
  // and Dockerfile.scheduler were removed in Phase 4.
  { src: "src/agent-scheduler/index.ts", out: "dist/agent-scheduler/index.js" },
  // RFC H: switchroom-auth-broker singleton. Bundled into the image as
  // /opt/switchroom/dist/auth-broker/index.js; Dockerfile.auth-broker
  // sets CMD to `bun` on the bundle. No native deps.
  { src: "src/auth/broker/index.ts", out: "dist/auth-broker/index.js" },
  // RFC C Phase 1: host-control daemon. Bundled as a node-target
  // file the operator launches via a systemd user unit (see RFC
  // C §5.1). NOT baked into any docker image — the daemon runs
  // on the host, not inside a container.
  { src: "src/host-control/main.ts", out: "dist/host-control/main.js" },
];
for (const entry of serverEntries) {
  const srcAbs = resolve(root, entry.src);
  const outAbs = resolve(root, entry.out);
  const outDirAbs = dirname(outAbs);
  mkdirSync(outDirAbs, { recursive: true });
  // Skip the entry silently if the source doesn't exist (e.g. kernel-server
  // is being added in a separate slice). Phase 1b will fail loudly via
  // tests/docker/build-log.txt if a target image's CMD points at a
  // missing bundle.
  try {
    execSync(
      `bun build ${JSON.stringify(srcAbs)} --outfile ${JSON.stringify(outAbs)} --target node --external better-sqlite3 --external node-cron`,
      { stdio: "inherit", cwd: root }
    );
    console.log(`[build] bundled ${entry.src} -> ${entry.out}`);
  } catch (err) {
    console.warn(`[build] WARN: skipped ${entry.src} -> ${entry.out}: ${err.message}`);
  }
}

console.log("[build] done");
