#!/usr/bin/env node
// Build script for npm publish — bundles CLI + fixes shebang for Node.
// Runs under bun (preferred) or node (with esbuild fallback if bun missing).
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, chmodSync, mkdirSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "dist/cli");
const outFile = resolve(outDir, "switchroom.js");

// --- Build-time constants ---------------------------------------------------
// Emit src/build-info.ts so the runtime can import VERSION + git metadata.
// On a fresh checkout outside git (npm consumer tarball), gracefully fall
// back to null git fields and version-only data.
function tryGit(cmd) {
  try {
    return execSync(cmd, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function generateBuildInfo() {
  const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"));
  const version = pkg.version;

  const inGit = tryGit("git rev-parse --is-inside-work-tree") === "true";

  const commitSha = inGit ? tryGit("git rev-parse --short HEAD") : null;
  const commitDate = inGit ? tryGit("git log -1 --format=%cI") : null;
  const subject = inGit ? tryGit("git log -1 --pretty=%s") : null;
  const prMatch = subject ? subject.match(/\(#(\d+)\)\s*$/) : null;
  const latestPr = prMatch ? Number(prMatch[1]) : null;

  // Commits ahead of nearest tag. `null` if no tags exist or git missing.
  let commitsAhead = null;
  if (inGit) {
    const lastTag = tryGit("git describe --tags --abbrev=0");
    if (lastTag) {
      const ahead = tryGit(`git rev-list --count ${lastTag}..HEAD`);
      commitsAhead = ahead != null ? Number(ahead) : null;
    }
  }

  const out = `// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.
// Tracked in git so \`tsc --noEmit\` works on a fresh clone before \`npm run build\`.
// Values are refreshed every time \`npm run build\` runs.

export const VERSION: string = ${JSON.stringify(version)};
export const COMMIT_SHA: string | null = ${JSON.stringify(commitSha)};
export const COMMIT_DATE: string | null = ${JSON.stringify(commitDate)};
export const LATEST_PR: number | null = ${JSON.stringify(latestPr)};
export const COMMITS_AHEAD_OF_TAG: number | null = ${JSON.stringify(commitsAhead)};
`;
  writeFileSync(resolve(root, "src/build-info.ts"), out);
  console.log(
    `[build] generated src/build-info.ts (v${version}` +
      (commitSha ? ` · ${commitSha}` : "") +
      (commitsAhead != null ? ` · +${commitsAhead}` : "") +
      `)`
  );
}

generateBuildInfo();

console.log("[build] cleaning dist/");
rmSync(resolve(root, "dist"), { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

// Prefer bun (already a dev dep / runtime). Fall back to a clear error if missing.
let hasBun = false;
try {
  execSync("bun --version", { stdio: "ignore" });
  hasBun = true;
} catch {}

if (!hasBun) {
  console.error("[build] bun is required to build. Install from https://bun.sh");
  process.exit(1);
}

console.log("[build] bundling bin/switchroom.ts -> dist/cli/switchroom.js");
execSync(
  `bun build ${JSON.stringify(resolve(root, "bin/switchroom.ts"))} --outdir ${JSON.stringify(outDir)} --target node`,
  { stdio: "inherit", cwd: root }
);

// Rewrite shebang from `node` to `bun` — bun:sqlite and other bun: imports
// are not polyfillable in Node, and bun is already a hard runtime dependency
// (broker uses it explicitly, gateway runs `bun gateway.ts`, build itself
// requires `bun install`). Running the bundle under node produces an
// immediate ERR_UNSUPPORTED_ESM_URL_SCHEME 'bun:' error.
console.log("[build] rewriting shebang -> bun");
let src = readFileSync(outFile, "utf8");
if (src.startsWith("#!/usr/bin/env node")) {
  src = src.replace(/^#!\/usr\/bin\/env node/, "#!/usr/bin/env bun");
  writeFileSync(outFile, src);
}
chmodSync(outFile, 0o755);

console.log("[build] done");
