/**
 * The single registry of "this inbound carries an approval OUTCOME".
 *
 * An approval outcome is a synthetic inbound that reports the RESULT of an
 * operator decision the agent is blocked on: a vault grant approved/denied,
 * a secret provided/declined, a mental-model proposal applied, a button tap.
 * It is structurally different from an ordinary chat message in one way that
 * matters to the inbound buffer: **the operator cannot resend it.** If a
 * `vault_grant_approved` is dropped, telling the user "please resend that
 * message" is meaningless — the tap already happened, the grant already
 * exists, and the agent waits forever for a wake-up that will never come.
 *
 * That asymmetry is why cap eviction in `pending-inbound-buffer.ts` may not
 * pick its victim blindly. An ordinary user message is resendable; an
 * approval outcome is not. So the buffer evicts the oldest NON-outcome first
 * and only touches an outcome when there is genuinely nothing else to drop.
 *
 * Membership is deliberately a closed literal set rather than a prefix/regex
 * match on `meta.source`: a new source string must be classified by a human
 * (or an agent reading this comment), not silently inherit protection from a
 * naming coincidence. The set is exhaustive against `telegram-plugin/gateway/`
 * as of this commit.
 *
 * No imports beyond the inbound type. The set, the predicate and the notice
 * builder are pure, so the buffer hot path can import them freely;
 * `createApprovalOutcomeDropNotifier` is the one stateful export (the gateway's
 * re-entrancy latch) and lives here rather than inline in `gateway.ts` so the
 * production wiring is the thing tests drive, not a copy of it.
 */

import type { InboundMessage } from './ipc-protocol.js'

/**
 * `meta.source` values that identify an inbound as an approval outcome.
 *
 * Grepped exhaustively from `telegram-plugin/gateway/` (both quote styles —
 * the `mental_model_proposal_*` builders use double quotes, which is how an
 * earlier single-quote-only survey missed them).
 *
 * Deliberately EXCLUDED, with reasons:
 *   - `missed_approval_retry` — carries no verdict. It ASKS the agent to
 *     re-attempt actions that timed out (`missed-approvals-card.ts:117-161`),
 *     and the operator can tap "retry" again. Resendable ⇒ ordinary.
 *   - `obligation_represent` / `subagent_handback` / `subagent_progress` /
 *     `resume_*` / `warmup` / `reaction` / `bridge_dead_restart` — internal
 *     nudges and lifecycle wake-ups, all regenerated by their own sweeps.
 *
 * `eval_case_applied` / `eval_case_rejected` / `eval_case_apply_failed` are
 * listed AHEAD of the branch that introduces them. Listing an unused source
 * is inert (nothing ever carries it), and it removes any ordering constraint
 * between the two changes — the alternative is a window where eval-case
 * verdicts are evictable.
 *
 * `eval_case_suppressed` is protected for the SAME reason, and it is the one
 * member that is not a verdict card at all. It is the gateway's own notice
 * that a re-proposed eval case was dropped against a live dismissal — the
 * agent's turn is blocked on it and NO sweep regenerates it (it fires exactly
 * once, at the moment of suppression, and the suppression path posts no card).
 * Unprotected it would be tier-1's preferred victim, so a cap overflow would
 * restore the silent block the notice exists to close.
 */
export const APPROVAL_OUTCOME_SOURCES: ReadonlySet<string> = Object.freeze(
  new Set([
    // vault grant decisions (#1150 — the original dropped-wake-up class)
    'vault_grant_approved',
    'vault_grant_denied',
    'vault_grant_timeout',
    // vault save decisions
    'vault_save_completed',
    'vault_save_discarded',
    'vault_save_failed',
    'vault_save_timeout',
    // secret-request decisions
    'secret_provided',
    'secret_declined',
    'secret_provide_failed',
    'secret_request_timeout',
    // mental-model proposal decisions
    'mental_model_proposal_applied',
    'mental_model_proposal_denied',
    'mental_model_proposal_failed',
    'mental_model_propose_timeout',
    // skill proposal decision
    'skill_proposal_apply',
    // eval-case proposal decisions (forward-listed; see doc comment)
    'eval_case_applied',
    'eval_case_rejected',
    'eval_case_apply_failed',
    // #4664's suppressed-proposal notice. Not itself a tap, but it reports the
    // standing effect of one the operator ALREADY made (the Dismiss that
    // recorded the rejection), and it is the only thing that ends the agent's
    // wait — see the doc comment above.
    'eval_case_suppressed',
  ]),
) as ReadonlySet<string>

/**
 * `meta.source` stamped on the synthetic notice the gateway pushes when an
 * approval outcome had to be dropped anyway (every buffered entry was an
 * outcome). Deliberately NOT a member of `APPROVAL_OUTCOME_SOURCES`: the
 * notice must be the PREFERRED victim of the next overflow, which is what
 * structurally bounds the notice→evict→notice recursion.
 */
export const APPROVAL_OUTCOME_DROPPED_SOURCE = 'approval_outcome_dropped'

/**
 * True when `msg` reports the result of an operator decision.
 *
 * TWO conditions, both required — a button tap has NO `meta.source` at all.
 * `agent-button-callback-handler.ts:123-133` stamps only
 * `meta.button_callback = 'true'` (plus `button_callback_data` / `button_text`),
 * so a source-only check silently leaves every agent-card tap evictable.
 */
export function isApprovalOutcome(msg: InboundMessage): boolean {
  const meta = msg.meta
  if (meta == null) return false
  if (meta.source != null && APPROVAL_OUTCOME_SOURCES.has(meta.source)) return true
  return meta.button_callback === 'true'
}

/** Human label for an outcome in logs / notices. Taps carry no source. */
export function approvalOutcomeLabel(msg: InboundMessage): string {
  const src = msg.meta?.source
  if (src != null && src !== '') return src
  if (msg.meta?.button_callback === 'true') return 'button_callback'
  return '-'
}

/**
 * Build the synthetic inbound that tells the agent an approval outcome was
 * dropped, so it stops waiting on a wake-up that is never arriving. Pure.
 *
 * It names the dropped source(s) rather than paraphrasing, because the agent's
 * next move depends on which one it was (a dropped `vault_grant_approved`
 * means "retry the vault read and see if the grant exists"; a dropped
 * `secret_declined` means "the operator said no").
 */
export function buildApprovalOutcomeDroppedInbound(opts: {
  agent: string
  chatId: string
  threadId?: number
  sources: string[]
  nowMs?: number
}): InboundMessage {
  const ts = opts.nowMs ?? Date.now()
  const list = opts.sources.length > 0 ? opts.sources.join(', ') : 'unknown'
  const plural = opts.sources.length === 1 ? 'an approval outcome' : 'approval outcomes'
  const msg: InboundMessage = {
    type: 'inbound',
    chatId: opts.chatId,
    ...(opts.threadId != null ? { threadId: opts.threadId } : {}),
    messageId: ts,
    user: 'gateway',
    userId: 0,
    ts,
    text:
      `⚠️ Your inbound buffer overflowed while every queued message was ${plural}, ` +
      `so the oldest had to be dropped: ${list}. Do NOT keep waiting on it — ` +
      `re-check the underlying state directly (e.g. retry the vault read to see ` +
      `whether the grant exists) and tell the operator plainly what was lost.`,
    meta: {
      source: APPROVAL_OUTCOME_DROPPED_SOURCE,
      agent: opts.agent,
      ...(opts.threadId != null ? { message_thread_id: String(opts.threadId) } : {}),
      dropped_sources: list,
      dropped_count: String(opts.sources.length),
    },
  }
  return msg
}

/** Max follow-up notice hops per burst. See `createApprovalOutcomeDropNotifier`. */
export const APPROVAL_OUTCOME_NOTICE_HOPS = 2

/**
 * Build the `onEvictCritical` handler the gateway wires into the pending
 * inbound buffer: log at a distinct greppable tag, then enqueue ONE synthetic
 * notice naming every outcome dropped since the last notice.
 *
 * Two properties this exists to guarantee, both of which a hand-inlined
 * version in `gateway.ts` would get wrong:
 *
 *  - **Never pushes inside the `push` frame.** `onEvictCritical` is invoked
 *    from the middle of `push`, on a queue sitting at cap. Pushing there
 *    recurses. Every enqueue goes through `queueMicrotask`.
 *  - **Terminates.** Deferring alone does not stop recursion, it only turns a
 *    stack overflow into an unbounded microtask loop. Termination is
 *    structural: the notice carries `approval_outcome_dropped`, which is NOT a
 *    member of `APPROVAL_OUTCOME_SOURCES`, so the moment one is resident it
 *    becomes the PREFERRED eviction victim and no further critical eviction can
 *    fire until it drains. The `scheduled` latch collapses a burst into one
 *    notice, and `hops` is a hard budget on top of the structural bound so a
 *    future change to victim selection degrades into a truncated chain rather
 *    than a spin.
 *
 * KNOWN COST, accepted deliberately: in the pathological state (every one of
 * the 32 slots is a fresh approval outcome) the notice's own push evicts one
 * MORE outcome to make room for itself. So that state costs two dropped
 * outcomes instead of one. The exchange is that the agent is TOLD — the
 * alternative is 32 resident outcomes and an agent blocked forever on a
 * wake-up that was silently discarded. Reaching this state at all requires 32
 * simultaneously-undelivered operator decisions for one agent.
 */
export function createApprovalOutcomeDropNotifier(opts: {
  /** Enqueue the notice. Wired to the buffer's own `push`. */
  push: (agent: string, msg: InboundMessage) => void
  log?: (line: string) => void
  /** Defer seam. Defaults to `queueMicrotask`. */
  defer?: (fn: () => void) => void
  nowMs?: () => number
  hops?: number
}): (agent: string, evicted: InboundMessage) => void {
  const log = opts.log ?? ((line: string) => process.stderr.write(line))
  const defer = opts.defer ?? ((fn: () => void) => queueMicrotask(fn))
  const hops = opts.hops ?? APPROVAL_OUTCOME_NOTICE_HOPS
  /** agent → labels of outcomes dropped since the last notice was built. */
  const pending = new Map<string, string[]>()
  /** agent → a notice enqueue is already scheduled (the re-entrancy latch). */
  const scheduled = new Set<string>()

  return (agent, evicted) => {
    const label = approvalOutcomeLabel(evicted)
    log(
      `telegram gateway: APPROVAL-OUTCOME-DROPPED agent=${agent} source=${label} ` +
      `chat=${evicted.chatId} ts=${evicted.ts}\n`,
    )
    const list = pending.get(agent) ?? []
    list.push(label)
    pending.set(agent, list)
    if (scheduled.has(agent)) return
    scheduled.add(agent)
    const chatId = evicted.chatId
    const threadId = evicted.threadId

    const flush = (budget: number): void => {
      // CUMULATIVE, and deliberately not cleared before the push: the notice we
      // are about to enqueue can itself be the entry a later overflow evicts
      // (it is the preferred victim, by design). If each hop named only the
      // drops since the last one, the surviving notice would omit the earliest
      // dropped source — the one the agent is most likely to be blocked on. So
      // every hop restates the whole burst and the list is cleared only when
      // the chain ends.
      const sources = [...(pending.get(agent) ?? [])]
      const before = sources.length
      try {
        opts.push(
          agent,
          buildApprovalOutcomeDroppedInbound({
            agent,
            chatId,
            ...(threadId != null ? { threadId } : {}),
            sources,
            ...(opts.nowMs != null ? { nowMs: opts.nowMs() } : {}),
          }),
        )
      } catch (e) {
        log(`telegram gateway: APPROVAL-OUTCOME-DROPPED notice push failed: ${String(e)}\n`)
      } finally {
        scheduled.delete(agent)
      }
      // The push above ran against a queue at cap, so it may itself have
      // evicted one more outcome (re-entering this handler with the latch still
      // set, which recorded the label but scheduled nothing). A GROWN list is
      // the signal that happened. Re-state, once more, then stop.
      if (budget > 0 && (pending.get(agent)?.length ?? 0) > before) {
        scheduled.add(agent)
        defer(() => flush(budget - 1))
      } else {
        pending.delete(agent)
      }
    }
    defer(() => flush(hops))
  }
}
