// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.
// Tracked in git so `tsc --noEmit` works on a fresh clone before `npm run build`.
// Values are refreshed every time `npm run build` runs.

export const VERSION: string = "0.3.0";
export const COMMIT_SHA: string | null = "c0fb1c0";
export const COMMIT_DATE: string | null = "2026-04-27T23:24:36+10:00";
export const LATEST_PR: number | null = 147;
export const COMMITS_AHEAD_OF_TAG: number | null = 50;
